
// Note: this public configuration was not generated by an autoconf configuration script.

#pragma once
#define HAVE_CONFIG_H
#define OPERATING_SYSTEM__VERSION__MICROSOFT__COMPATIBILITY OPERATING_SYSTEM__VERSION__MICROSOFT__COMPATIBILITY__1998
