#! /bin/sh

# This script converts msvc-2005 projects and solutions to msvc-2008

cd $(dirname $0)/.. &&

# converts the projects
for f in $(find . -name \*.msvc-2005.vcproj)
do
	if grep -F 'Keyword="MakeFileProj"' $f 1> /dev/null
	then
		continue
	fi &&
	echo $f | sed 's/msvc-2005/msvc-{2005->2008}/' &&
	sed \
		-e s/msvc-2005/msvc-2008/g \
		-e 's/Version=\"8[.,]00\"/Version=\"9\.00\"/' \
		< $f > $(echo $f | sed s/msvc-2005/msvc-2008/) ||
	break
done &&

# converts the solutions
for f in  $(find . -name \*.msvc-2005.sln)
do
	echo $f | sed 's/msvc-2005/msvc-{2005->2008}/' &&
	sed \
		-e s/msvc-2005/msvc-2008/g \
		-e 's/^Microsoft Visual Studio Solution File, Format Version 9.00$/Microsoft Visual Studio Solution File, Format Version 10.00/' \
		-e 's/^# Visual Studio 2005$/# Visual Studio 2008/' \
		< $f > $(echo $f | sed s/msvc-2005/msvc-2008/) ||
	break
done
