///\file
///
/// This public configuration was not generated by an autoconf configuration script.
/// To disable an option, instead of undefining the preprocessor symbol, rather set it to 0.
/// This is because some options, when undefined, will systematically trigger #error in each part of the code concerned.
///
#pragma once


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///\name string describing the configuration options
///\{

	/// string describing the configuration options.
	#define PSYCLE__CONFIGURATION__DESCRIPTION \
		/* feature options */ \
		"read_write_mutex = "          UNIVERSALIS__COMPILER__STRINGIZED(PSYCLE__CONFIGURATION__READ_WRITE_MUTEX) UNIVERSALIS__OPERATING_SYSTEM__EOL \
		"fpu exceptions = "            UNIVERSALIS__COMPILER__STRINGIZED(PSYCLE__CONFIGURATION__FPU_EXCEPTIONS  ) UNIVERSALIS__OPERATING_SYSTEM__EOL \
		"volume column = "             UNIVERSALIS__COMPILER__STRINGIZED(PSYCLE__CONFIGURATION__VOLUME_COLUMN   ) UNIVERSALIS__OPERATING_SYSTEM__EOL \
		"rms vus = "                   UNIVERSALIS__COMPILER__STRINGIZED(PSYCLE__CONFIGURATION__RMS_VUS         ) UNIVERSALIS__OPERATING_SYSTEM__EOL \
		/* package options */ \
		"platform-specific code = "    UNIVERSALIS__COMPILER__STRINGIZED(PSYCLE__QUAQUAVERSALIS                 ) UNIVERSALIS__OPERATING_SYSTEM__EOL \
		"debugging = "                                                   PSYCLE__CONFIGURATION__DEBUG             UNIVERSALIS__OPERATING_SYSTEM__EOL \
		//

	/// value to show in the string describing the configuration options (PSYCLE__CONFIGURATION__DESCRIPTION).
	///\see PSYCLE__CONFIGURATION__DESCRIPTION
	/// this is needed because NDEBUG might be #defined, but not to a non-zero value.
	#if defined NDEBUG
		#define PSYCLE__CONFIGURATION__DEBUG "off"
	#else
		#define PSYCLE__CONFIGURATION__DEBUG "on"
	#endif

	/// end-of-line character sequence on the platform.
	///\todo get this definition from universalis after a work around for msvc's resource compiler parsing bug is setup.
	#ifndef UNIVERSALIS__OPERATING_SYSTEM__EOL
		#ifdef DIVERSALIS__OPERATING_SYSTEM__MICROSOFT
			#define UNIVERSALIS__OPERATING_SYSTEM__EOL "\r\n"
	//	#elif defined DIVERSALIS__OPERATING_SYSTEM__APPLE && DIVERSALIS__OPERATING_SYSTEM__VERSION__MAJOR < 10 // before bsd-unix (darwin)
	//			#define UNIVERSALIS__OPERATING_SYSTEM__EOL "\r"
		#else
			#define UNIVERSALIS__OPERATING_SYSTEM__EOL "\n"
		#endif
	#endif

	#include <universalis/compiler/stringized.hpp>

///\}
