// -*- mode:c++; indent-tabs-mode:t -*-
#pragma once
// This is just an empty file to avoid build failures for people having their own build system.
// The sources are generally able to build without specifying anything in this file,
// but this file exist as a placeholder for possible platform-specific tweaks.
#define UNIVERSALIS__COMPILER__DETAIL__PRAGMATIC__DEMANGLE 1
#define UNIVERSALIS__COMPILER__EXCEPTIONS__ELLIPSIS 1
#define UNIVERSALIS__OPERATING_SYSTEM__DETAIL__CHECK_VERSION 1
#define UNIVERSALIS__OPERATING_SYSTEM__DYNAMIC_LINK__RESOLVER 1
#define UNIVERSALIS__OPERATING_SYSTEM__EXCEPTIONS__CODE_DESCRIPTION 1
#define UNIVERSALIS__OPERATING_SYSTEM__CLOCKS 1
#define UNIVERSALIS__OPERATING_SYSTEM__EXCEPTION 1
#define UNIVERSALIS__OPERATING_SYSTEM__LOGGERS 1
#define UNIVERSALIS__OPERATING_SYSTEM__PATHS 1
#define UNIVERSALIS__OPERATING_SYSTEM__TERMINAL 1
#define UNIVERSALIS__PROCESSOR__EXCEPTION 1
#define UNIVERSALIS__PROCESSOR__ATOMIC__COMPARE_AND_SWAP 1
#define UNIVERSALIS__PROCESSOR__EXCEPTIONS__CODE_DESCRIPTION 1
#define UNIVERSALIS__PROCESSOR__EXCEPTION 1
#define UNIVERSALIS__STANDARD_LIBRARY__DETAIL__ALLOCATORS 1
#define UNIVERSALIS__STANDARD_LIBRARY__EXCEPTIONS__CODE_DESCRIPTION 1
#define UNIVERSALIS__EXCEPTION 1

