#! /usr/bin/env python

import os, sys

def do_one_file(path):
	f = file(path, 'r')
	lines = f.readlines()
	f.close()
	replaced = False
	for line in lines:
		for char in line:
			if char == '\r':
				print sys.argv[0] + ':', 'carriage return character found in', path
				return

if __name__ == '__main__':
	for path in sys.argv[1:]:
		if not os.path.exists(path): print sys.argv[0] + ':', path + ': No such file or directory'
		else: do_one_file(path)
