#! /bin/sh

svn propset svn:eol-style native $(find $(dirname $0) \( \
	-name \*.cpp -or \
	-name \*.hpp -or \
	-name \*.h -or \
	-name \*.rc -or \
	-name \*.py -or \
	-name \*.txt -or \
	-name \*.text -or \
	-name \*.html -or \
	-name SConstruct -or \
	-name README -or \
	-name INSTALL -or \
	-name LICENSE -or \
	-name AUTHORS -or \
	-name NEWS -or \
	-name TODO -or \
	-name HACKING -or \
	-name ChangeLog \
\))
