#! /bin/sh
set -x
g++                              main.cpp        -o out-native      -O3
$(llvm-config --bindir)/llvm-g++ main.cpp        -o out-llvm-direct -O3
$(llvm-config --bindir)/llvm-g++ main.cpp        -o out-main.bc     -O4 -emit-llvm -c
$(llvm-config --bindir)/llvm-ld  out-main.bc     -o out-llvm-ld     -O4 -native -lstdc++
$(llvm-config --bindir)/llvm-g++ main.cpp        -o out-main.ll     -O4 -S
$(llvm-config --bindir)/llvm-dis out-main.bc     -o out-main.bc.ll  -f
diff out-main.ll out-main.bc.ll
$(llvm-config --bindir)/llvm2cpp out-main.bc     -o out-main.bc.cpp -f -gen-program
g++                              out-main.bc.cpp -o out-llvm-cxx    -O3 $(llvm-config --cxxflags --ldflags --libs core)
true
