#! /usr/bin/env scons

import os, packageneric as jerrycan

if False:
	package = packageneric.debian.changelog.package_name()

	output = packageneric.output

	prefix = os.path.join(output, 'install')
	includedir = os.path.join(prefix, 'include')
	pkgincludedir = os.path.join(includedir, package)

	BuildDir(os.path.join(output, 'build', 'scons'), 'src', duplicate=0)

	env = Environment()
	
	diversalis = jerrycan.InternalModule(env)
	diversalis.set_name('diversalis')
	diversalis.set_version([0, 0, 0])
	diversalis.compiler_flags.append('-O0')
	diversalis.compiler_flags.append('-ggdb3')
	diversalis.get_headers().add(jerrycan.Find('src', 'diversalis', '*.hpp'))

	diversalis_package = jerrycan.InternalModulePackage(env)
	diversalis_package.set_name('diversalis')
	diversalis_package.set_version([0, 0, 0])
	diversalis_package.get_modules().append(diversalis)

	
	env.Install(pkgincludedir, diversalis.get_headers())
	env.Install(install.include, universalis)
	env.Alias('install', prefix)
