///\file
///
/// This public configuration was not generated by an autoconf configuration script.
/// To disable an option, instead of undefining the preprocessor symbol, rather set it to 0.
/// This is because some options, when undefined, will systematically trigger #error in each part of the code concerned.
///
#pragma once



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///\name configuration feature options
/// in autoconf's terminology, these are "feature" options, that you set using "--enable" or "--disable" on configure's command line.
///\{



	/// turn on type-safe compilation.
	/// for example, it makes some of the typedefs "strong",
	/// i.e. wrapped by a class with a implicit convertion operator to the pointee type so it can be used as is by the lower layer,
	/// but which has an explicit constructor, so higher layer has to know the semantic of the type.
	#define PSYCLE__CONFIGURATION__TYPE_SAFE 0

	/// turn on tight access control of member data in classes.
	/// ... getting rid of every public data member and low-level interface.
	#define PSYCLE__CONFIGURATION__TIGHT_MEMBER_ACCESS_CONTROL 0

	/// implementation of psycle::host::Song's lock using boost 1.3's read_write_mutex.
	#define PSYCLE__CONFIGURATION__READ_WRITE_MUTEX 0
		// boost::thread::read_write_mutex has been removed from boost.thread around version 1.33.1
		#ifndef DIVERSALIS__COMPILER__RESOURCE // workaround msvc's resource compiler's boggus preprocessor
			#if PSYCLE__CONFIGURATION__READ_WRITE_MUTEX
				#include <boost/version.hpp>
				#if BOOST_VERSION != 103200
					#undef  PSYCLE__CONFIGURATION__READ_WRITE_MUTEX
					#define PSYCLE__CONFIGURATION__READ_WRITE_MUTEX 0
				#endif
			#endif
		#endif



	/// JAZ: Define to 1 to enable the volume column for XMSampler. It will also make the machine column in the pattern to show
	///      the values of the volume column instead.
	#define PSYCLE__CONFIGURATION__VOLUME_COLUMN 0



	/// Test for RMS Vu's
	#define PSYCLE__CONFIGURATION__RMS_VUS 0



	/// unmasks fpu exceptions
	/// [JAZ] : I have experienced crashes with this option enabled, which didn't seem to come from the code itself.
	/// [JAZ]   It could be that the exception code handling has a bug somewhere.
	#define PSYCLE__CONFIGURATION__FPU_EXCEPTIONS 0



	/// [bohan] just testing boost.serialization a bit
	#define PSYCLE__CONFIGURATION__SERIALIZATION 1
		// this is a test, don't build it in releases
		#if defined NDEBUG
			#undef  PSYCLE__CONFIGURATION__SERIALIZATION
			#define PSYCLE__CONFIGURATION__SERIALIZATION 0
		#endif
		// no serialization on boost version 1.32 and below
		#ifndef DIVERSALIS__COMPILER__RESOURCE // workaround msvc's resource compiler's boggus preprocessor
			#if PSYCLE__CONFIGURATION__SERIALIZATION
				#include <boost/version.hpp>
				#if BOOST_VERSION < 103301
					#undef  PSYCLE__CONFIGURATION__SERIALIZATION
					#define PSYCLE__CONFIGURATION__SERIALIZATION 0
				#endif
			#endif
		#endif



///\}



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///\name configuration package options
/// in autoconf's terminology, these are "package" options, that you set using "--with" or "--without" on configure's command line.
///\{



	/// enables platform-specific code.
	///
	/// quaquaversalis means providing, on each diversalis direction, a specific implementation, as opposed to the unique universalis one.
	/// in other words:
	/// - when defined, psycle's preprocessor conditions will sometimes select source code which is specific to the platform.
	/// - when undefined, psycle's preprocessor conditions will always select source code with is portable, if possible.
	///
	/// quaquaversalis is configurable at several layers:
	/// for example if PSYCLE__QUAQUAVERSALIS is unset, the sources will prefer to make use of universalis rather than platform-specific code directly,
	/// but universalis itself may use platform-specific code if UNIVERSALIS__QUAQUAVERSALIS is set.
	///
	#define PSYCLE__QUAQUAVERSALIS 1



///\}
