#! /usr/bin/env scons

import os, packagerrycan

package = packageneric.debian.changelog.package_name()

output = packageneric.output

prefix = os.path.join(output, 'install')
includedir = os.path.join(prefix, 'include')
pkgincludedir = os.path.join(includedir, package)

BuildDir(os.path.join(output, 'build', 'scons'), 'src', duplicate=0)

module = packageneric.Module()

for file in packageneric.find('src', '*.hpp'):
	module.headers.add(file)
