//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Psycle.rc
//
#define IDR_MAINFRAME                   100
#define IDD_SAVESONG                    102
#define IDD_ABOUTBOX                    104
#define IDD_GREETS                      105
#define IDB_SPLASH                      106
#define IDD_INFO                        107
#define IDB_CPU                         108
#define IDD_MIDI_MONITOR                109
#define IDD_DSOUNDCONFIG                110
#define IDD_WAVEOUTCONFIG               111
#define IDB_DIRECTX                     112
#define IDD_OUTPUT                      113
#define IDD_DIRECTORIES                 114
#define IDD_CONFIGURATION               115
#define IDD_SKIN                        116
#define IDD_KEYCONFIG                   117
#define IDD_SONGPROP                    120
#define IDD_PSYBAR                      122
#define IDB_LESS                        123
#define IDB_LESSLESS                    124
#define IDB_MORE                        125
#define IDB_MOREMORE                    126
#define IDB_LLEFT                       127
#define IDB_LRIGHT                      128
#define IDD_PSYBAR2                     130
#define IDD_SEQUENCER                   131
#define IDB_PLUS                        132
#define IDB_MINUS                       133
#define IDR_WAVEFRAME                   134
#define IDR_MACHINEFRAME                135
#define IDD_INSTRUMENT                  136
#define IDD_ENVDIALOG                   137
#define IDD_PATDLG                      138
#define IDD_WIREDIALOG                  139
#define IDD_NEWVAL                      140
#define IDD_MACPROP                     141
#define IDD_NEWMACHINE                  142
#define IDB_MACHINETYPE                 143
#define IDD_GEAR_PSYCHOSC               144
#define IDB_PSYCHOSC                    145
#define IDD_GEARDISTORT                 146
#define IDB_DIST                        147
#define IDD_GEAR_TRACKER                148
#define IDB_SAMPLER                     149
#define IDD_GEAR_DELAY                  150
#define IDB_DALAYDELAY                  151
#define IDB_SPEAKER                     152
#define IDD_GEAR_FILTER                 153
#define IDD_GEAR_GAINER                 154
#define IDD_GEAR_FLANGER                155
#define IDB_FLANGER                     156
#define IDD_MASTERDLG                   157
#define IDD_VSTRACK                     158
#define IDR_VSTFRAME                    159
#define IDB_KNOB                        160
#define IDB_STUFF                       161
#define IDR_POPUPMENU                   162
#define IDD_PRESETS                     164
#define IDD_WAVED_AMPLIFY               165
#define IDD_INST_EDITOR                 172
#define IDC_CONFIG_DEVICE               1000
#define IDC_SLIDER1                     1001
#define IDC_CONFIG_SAMPLERATE           1002
#define IDC_SLIDER2                     1003
#define IDC_CONFIG_BUFNUM               1004
#define IDC_SLIDER3                     1005
#define IDC_CONFIG_BUFSIZE              1006
#define IDC_SLIDER4                     1007
#define IDC_TEXT1                       1008
#define IDC_CONFIG_DITHER               1009
#define IDC_F_SLIDER1                   1010
#define IDC_SLIDER5                     1011
#define IDC_CONFIG_BUFNUM_SPIN          1012
#define IDC_STATIC1                     1013
#define IDC_F_SLIDER2                   1014
#define IDC_SLIDER6                     1015
#define IDC_CONFIG_BUFSIZE_SPIN         1016
#define IDC_STATIC2                     1017
#define IDC_F_SLIDER3                   1018
#define IDC_CONFIG_LATENCY              1019
#define IDC_STATIC3                     1020
#define IDC_F_SLIDER4                   1021
#define IDC_STATIC4                     1022
#define IDC_SLIDER9                     1023
#define IDC_SLIDER10                    1024
#define IDC_MACHINELIST                 1025
#define IDC_BUTTON1                     1026
#define IDC_BUTTON3                     1027
#define IDC_ENVELOPE                    1028
#define IDC_EDIT1                       1029
#define IDC_BUTTON14                    1030
#define IDC_BUTTON15                    1031
#define IDC_EDIT3                       1032
#define IDC_BROWSER                     1033
#define IDC_NAMELABEL                   1034
#define IDC_BUTTON16                    1035
#define IDC_EDIT4                       1036
#define IDC_FONTC                       1037
#define IDC_DESCLABEL                   1038
#define IDC_INSTEDIT                    1039
#define IDC_BUTTON17                    1040
#define IDC_BUTTON11                    1041
#define IDC_VSTEDIT                     1042
#define IDC_BUTTON2                     1043
#define IDC_BUTTON18                    1044
#define IDC_PLUGINEDIT                  1045
#define IDC_BUTTON4                     1046
#define IDC_BUTTON19                    1047
#define IDC_BUTTON5                     1048
#define IDC_BUTTON20                    1049
#define IDC_CHECK1                      1050
#define IDC_BUTTON6                     1051
#define IDC_BUTTON21                    1052
#define IDC_BUTTON12                    1053
#define IDC_BUTTON22                    1054
#define IDC_BUTTON13                    1055
#define IDC_TPBLABEL                    1056
#define IDC_BUTTON23                    1057
#define IDC_BPMLABEL                    1058
#define IDC_BUTTON24                    1059
#define IDC_LOOPOFF                     1060
#define IDC_BUTTON25                    1061
#define IDC_EDIT2                       1062
#define IDC_LOOPFORWARD                 1063
#define IDC_EDIT5                       1063
#define IDC_SPIN1                       1064
#define IDC_LAYER1                      1065
#define IDC_LAYER2                      1066
#define IDC_LAYER3                      1067
#define IDC_LAYER4                      1068
#define IDC_LAYER5                      1069
#define IDC_LAYER6                      1070
#define IDC_LAYER7                      1071
#define IDC_LAYER8                      1072
#define IDC_LAYER9                      1073
#define IDC_LAYER10                     1074
#define IDC_LAYER11                     1075
#define IDC_LAYER12                     1076
#define IDC_LAYER13                     1077
#define IDC_LAYER14                     1078
#define IDC_LAYER15                     1079
#define IDC_LAYER16                     1080
#define IDC_LAYERN                      1081
#define IDC_WAVENAME                    1082
#define IDC_INSTNUMBER                  1083
#define IDC_LOOPSTART                   1084
#define IDC_LOOPEND                     1085
#define IDC_STATUS                      1086
#define IDC_STEREO                      1087
#define IDC_LOOPTYPE                    1088
#define IDC_WAVELENGTH                  1089
#define IDC_VOLABEL                     1090
#define IDC_BUTTON7                     1091
#define IDC_INSTNAME                    1092
#define IDC_VOLABEL2                    1093
#define IDC_COMBO1                      1094
#define IDC_BUTTON8                     1095
#define IDC_NNA_COMBO                   1096
#define IDC_TRACKLABEL2                 1097
#define IDC_TRACKSLIDER2                1098
#define IDC_SLIDER_TIME                 1099
#define IDC_LABEL_LTIME                 1100
#define IDC_SLIDER_TIME2                1101
#define IDC_LABEL_LTIME2                1102
#define IDC_F_LABEL_L                   1103
#define IDC_F_LABEL_R                   1104
#define IDC_LABEL_MSL                   1105
#define IDC_AMPFRAME                    1106
#define IDC_A_A_LABEL                   1107
#define IDC_DRYLABEL                    1108
#define IDC_LABEL_MSR                   1109
#define IDC_A_D_LABEL                   1110
#define IDC_A_R_LABEL                   1111
#define IDC_WETLABEL                    1112
#define IDC_A_S_LABEL                   1113
#define IDC_AMPFRAME2                   1114
#define IDC_F_A_LABEL                   1115
#define IDC_F_D_LABEL                   1116
#define IDC_F_R_LABEL                   1117
#define IDC_F_S_LABEL                   1118
#define IDC_CUTOFF_LBL                  1119
#define IDC_LABELQ                      1120
#define IDC_A_A_LABEL7                  1121
#define IDC_LIST1                       1122
#define IDC_DRYSLIDER                   1123
#define IDC_WETSLIDER                   1124
#define IDC_RPAN                        1125
#define IDC_RCUT                        1126
#define IDC_PANSLIDER                   1127
#define IDC_RRES                        1128
#define IDC_CPUIDLE_LABEL               1129
#define IDC_CPUL                        1130
#define IDC_MCPULABEL                   1131
#define IDC_MCPULABEL2                  1132
#define IDC_MEM_RESO                    1133
#define IDC_MEM_RESO2                   1134
#define IDC_MEM_RESO3                   1135
#define IDC_MEM_RESO4                   1136
#define IDC_LVUM                        1137
#define IDC_RVUM                        1138
#define IDC_LABEL1                      1139
#define IDC_SSCOMBO2                    1140
#define IDC_LABEL2                      1141
#define IDC_TRACKCOMBO                  1142
#define IDC_LABEL3                      1143
#define IDC_BAR_COMBOGEN                1144
#define IDC_LABEL4                      1145
#define IDC_BAR_COMBOINS                1146
#define IDC_LABEL5                      1147
#define IDC_LABEL6                      1148
#define IDC_PRESETCOMBO                 1149
#define IDC_FRAMECLIP                   1150
#define IDC_CLIPBUT                     1151
#define IDC_DBLEVEL                     1152
#define IDC_LOADWAVE                    1153
#define IDC_EDITWAVE                    1154
#define IDC_WAVEBUT                     1155
#define IDC_B_DECGEN                    1156
#define IDC_B_INCGEN                    1157
#define IDC_B_DECWAV                    1158
#define IDC_B_INCWAV                    1159
#define IDC_CHECK4                      1160
#define IDC_LOOPEDIT                    1161
#define IDC_SEQLIST                     1162
#define IDC_INCSHORT                    1163
#define IDC_DECSHORT                    1164
#define IDC_SEQINS                      1165
#define IDC_SEQDEL                      1166
#define IDC_SEQCLR                      1167
#define IDC_SEQSPR                      1168
#define IDC_SEQ1                        1169
#define IDC_SAVEWAVE                    1169
#define IDC_SEQ2                        1170
#define IDC_SEQ3                        1171
#define IDC_INCPOS2                     1172
#define IDC_DECPOS2                     1173
#define IDC_DECPAT2                     1174
#define IDC_INCPAT2                     1175
#define IDC_DECLEN                      1176
#define IDC_INCLEN                      1177
#define IDC_SEQSLEN                     1178
#define IDC_DSOUND_DEVICE               1179
#define IDC_DSOUND_BUFNUM_EDIT          1180
#define IDC_DSOUND_BUFSIZE_SPIN         1181
#define IDC_DSOUND_BUFSIZE_EDIT         1182
#define IDC_DSOUND_BUFNUM_SPIN          1183
#define IDC_DSOUND_LATENCY              1184
#define IDC_DSOUND_SAMPLERATE_COMBO     1185
#define IDC_DSOUND_DITHER               1186
#define IDC_DRIVER                      1187
#define IDC_CONFIG                      1188
#define IDC_EXCLUSIVE                   1189
#define IDC_BROWSESONG                  1190
#define IDC_BROWSEINST                  1191
#define IDC_SONGEDIT                    1192
#define IDC_BROWSEVST                   1193
#define IDC_REFRESH                     1194
#define IDC_BROWSEPLUGIN                1195
#define IDC_DEC_TPB                     1196
#define IDC_INC_TPB                     1197
#define IDC_MUTE                        1198
#define IDC_LENGTH                      1199
#define IDC_FOLLOW                      1200
#define IDC_MULTICHANNEL_AUDITION       1201
#define IDC_BAR_GENFX                   1202
#define IDC_WRAP                        1203
#define IDC_BYTYPE                      1204
#define IDC_BYCLASS                     1205
#define IDC_ABOUTBMP                    1206
#define IDC_BYPASS                      1207
#define IDC_SAVE                        1208
#define IDC_DELETE                      1209
#define IDC_MIDI_DRIVER                 1210
#define IDC_BUFFER_USED                 1211
#define IDC_SYNC_DRIVER                 1212
#define IDC_BUFFER_CAPACITY             1213
#define IDC_SYNC_OFFSET                 1214
#define IDC_SYNC_ADJUST                 1215
#define IDC_MIDI_VERSION                1216
#define IDC_IMPORT                      1217
#define IDC_MIDI_HEADROOM               1218
#define IDC_PREVIEW                     1219
#define IDC_SYNC_LATENCY                1220
#define IDC_PRESETSLIST                 1221
#define IDC_EVENTS_LOST                 1222
#define IDC_MIDI_HEADROOM_SPIN          1223
#define IDF_PSYCLE_MIDI_ACTIVE          1224
#define IDC_EXPORT                      1225
#define IDF_RECEIVING_MIDI_DATA         1226
#define IDC_SOLO                        1227
#define IDF_SYNCRONISING                1228
#define IDC_VERSIONLABEL                1229
#define IDF_RESYNC_TRIGGERED            1230
#define IDC_DLLNAMELABEL                1230
#define IDC_KEY0                        1231
#define IDF_MIDI_SYNC_START             1232
#define IDC_CMDLIST                     1233
#define IDF_MIDI_SYNC_CLOCK             1234
#define IDC_MIDI_RECORD_NOTEOFF         1235
#define IDF_MIDI_SYNC_STOP              1236
#define IDC_MIDI_MACHINE_VIEW_SEQ_MODE  1237
#define IDF_EMULATED_SYNC_START         1238
#define IDC_PLAY_R_CTRL                 1239
#define IDF_EMULATED_SYNC_CLOCK         1240
#define IDC_FT2_HOME_END                1241
#define IDF_EMULATED_SYNC_STOP          1242
#define IDC_CENTERCURSOR                1243
#define IDF_SYNC_TICK                   1244
#define IDC_FT2DEL                      1245
#define IDC_SHIFTARROWS                 1246
#define IDC_CLEAR_EVENTS_LOST           1247
#define IDC_ROWC                        1248
#define IDC_CHANNEL_MAP                 1249
#define IDC_BEATC                       1250
#define IDC_CH1                         1251
#define IDC_4BEAT                       1252
#define IDC_CH2                         1253
#define IDC_FONTFACE                    1254
#define IDC_CH3                         1255
#define IDC_DOUBLEBUFFER                1256
#define IDC_CH4                         1257
#define IDC_CH5                         1258
#define IDC_CH6                         1259
#define IDC_CH7                         1260
#define IDC_CH8                         1261
#define IDC_CH9                         1262
#define IDC_CH10                        1263
#define IDC_CH11                        1264
#define IDC_CH12                        1265
#define IDC_CH13                        1266
#define IDC_CH14                        1267
#define IDC_CH15                        1268
#define IDC_CH16                        1269
#define IDC_INSTLABEL                   1270
#define IDC_CURSORDOWN                  1270
#define IDC_PARAM_INF_2                 1271
#define IDC_PARAM_INF_3                 1272
#define IDC_PARAM_INF_4                 1273
#define IDC_PARAM_INF_6                 1274
#define IDC_PARAM_INF_5                 1275
#define IDC_RESETCOLOURS                1276
#define IDC_HEADER                      1277
#define IDC_HEADERDLG                   1278
#define IDC_STEINBERGCOPY               1279
#define IDC_SHOWATSTARTUP               1280
#define IDC_AUXSELECT                   1281
#define IDC_AUTODEC                     1282
#define IDC_TAB1                        1283
#define IDC_INST_NUM                    1284
#define IDC_INST_MORE                   1285
#define IDC_INST_LESS                   1286
#define IDC_INST_NAME                   1287
#define IDC_REMOVE                      1288
#define IDC_SHOWDLLNAME                 1289
#define IDC_SHOWEFFNAME                 1291
#define ID_CONFIGURATION_FREEAUDIO      32772
#define ID_MACHINEVIEW                  32775
#define ID_VIEW_INSTRUMENTEDITOR        32778
#define ID_ABOUTPSYCLE                  32780
#define ID_BARPLAY                      32785
#define ID_BARSTOP                      32786
#define ID_RECORDB                      32794
#define ID_FILE_LOADSONG                32795
#define ID_FILE_SAVESONG                32796
#define ID_HELP_SALUDOS                 32798
#define ID_COPYPATTERN                  32799
#define ID_CUTPATTERN                   32800
#define ID_PASTEPATTERN                 32801
#define ID_CONFIGURATION_SETTINGS       32808
#define ID_FILE_SONGPROPERTIES          32809
#define ID_SHOWPSEQ                     32811
#define ID_NEWMACHINE                   32817
#define ID_PSYHELP                      32818
#define ID_SELECCION_ZOOM               32819
#define ID_SELECTION_FADEIN             32820
#define ID_SELECTION_FADEOUT            32821
#define ID_CUTWAVE                      32822
#define ID_SELECCION_ZOOMOUT            32823
#define ID_PATTERNVIEW                  32824
#define ID_PARAMETERS_RANDOMPARAMETERS  32825
#define ID_PARAMETERS_RESETPARAMETERS   32826
#define ID_PARAMETERS_COMMAND           32827
#define ID_PARAMETERS_SHOWPRESET        32828
#define ID_MACHINE_ABOUTTHISMACHINE     32830
#define ID_MACHINE_ABOUTPSYGEARV10      32831
#define ID_POP_UNDO                     32852
#define ID_POP_CUT                      32853
#define ID_POP_COPY                     32854
#define ID_POP_PASTE                    32855
#define ID_POP_INTERPOLATE              32856
#define ID_POP_CHANGEGENERATOR          32857
#define ID_POP_CHANGEINSTRUMENT         32858
#define ID_POP_TRANSPOSE1               32859
#define ID_POP_TRANSPOSE12              32861
#define ID_POP_TRANSPOSE_12             32862
#define ID_POP_PATTENPROPERTIES         32865
#define ID_POP_MIXPASTE                 32866
#define ID_BUTTONPLAYSEQBLOCK           32868
#define ID_POP_TRANSPOSE_1              32869
#define ID_AUTOSTOP                     32881
#define ID_INDICATOR_SIZE               32883
#define ID_INDICATOR_MODE               32884
#define ID_CPUPERFORMANCE               32885
#define ID_MIDI_MONITOR                 32886
#define ID_CONFIGURATION_KEYBOARD       32888
#define IDS_COULDNT_INITIALIZE_TIMER    32889
#define IDS_SONG_SAVED                  32890
#define IDS_ARE_YOU_SURE                32891
#define ID_FILE_IMPORT_XMFILE           32892
#define ID_SELECTION_NORMALIZE          32893
#define ID_SELECTION_REMOVEDC           32894
#define ID_SELECTION_AMPLIFY            32896
#define ID_SELECTION_REVERSE            32897
#define ID_SELECTION_SHOWALL            32898
#define ID_EDIT_DELETE                  32899
#define ID_CONVERT_MONO                 32900
#define ID_CONVERT_STEREO               32901
#define ID_FILE_RECENT_01               32902
#define ID_FILE_RECENT_02               32903
#define ID_FILE_RECENT_03               32904
#define ID_FILE_RECENT_04               32905
#define ID_FILE_RECENT_NONE             32906

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32909
#define _APS_NEXT_CONTROL_VALUE         1296
#define _APS_NEXT_SYMED_VALUE           52
#endif
#endif
