;------------------------------------------------------------------------------
;
;	Disassembly listing generated by PE Explorer version 1.99
;	Heaventools Software (http://www.heaventools.com)
;
;------------------------------------------------------------------------------
;
;  Name: .text (Code Section)
;  Virtual Address:    10001000h  Virtual Size:    00000722h
;  Pointer To RawData: 00001000h  Size Of RawData: 00001000h
;
 GetInfo:
  		mov	eax,CMachineInfo
  		retn
;------------------------------------------------------------------------------
  		Align	16
 CreateMachine:
  		push	00000010h
  		call	jmp_MSVCRT.dll!??2@YAPAXI@Z
  		add	esp,00000004h
  		test	eax,eax
  		jz 	CreateMachineZero
  		mov	ecx,eax
  		jmp	MachineConstructor
 CreateMachineZero:
  		xor	eax,eax
  		retn
;------------------------------------------------------------------------------
  		Align	16
 MachineConstructor:
  		push	FFFFFFFFh
  		push	L100016F8
  		mov	eax,fs:[00000000h]
  		push	eax
  		mov	fs:[00000000h],esp
  		push	ecx
  		push	esi
  		mov	esi,ecx
  		mov	[esp+04h],esi
  		push	00000018h
  		mov	dword ptr [esp+14h],00000000h
  		mov	dword ptr [esi],CMachineInterface
  		call	jmp_MSVCRT.dll!??2@YAPAXI@Z
  		mov	ecx,[esp+0Ch]
  		mov	[esi+04h],eax
  		add	esp,00000004h
  		mov	dword ptr [esi+0Ch],00000000h
  		mov	eax,esi
  		pop	esi
  		mov	fs:[00000000h],ecx
  		add	esp,00000010h
  		retn
;------------------------------------------------------------------------------
  		Align	16
 MachineDestructor:
  		push	esi
  		mov	esi,ecx
  		call	SUB_L100010B0
  		test	byte ptr [esp+08h],01h
  		jz 	L100010A8
  		push	esi
  		call	jmp_MSVCRT.dll!??3@YAXPAX@Z
  		add	esp,00000004h
 L100010A8:
  		mov	eax,esi
  		pop	esi
  		retn	0004h
;------------------------------------------------------------------------------
  		Align	4
 SUB_L100010B0:
  		push	FFFFFFFFh
  		push	L10001718
  		mov	eax,fs:[00000000h]
  		push	eax
  		mov	fs:[00000000h],esp
  		push	ecx
  		push	esi
  		mov	esi,ecx
  		mov	[esp+04h],esi
  		mov	dword ptr [esi],CMachineInterface
  		mov	eax,[esi+04h]
  		push	eax
  		mov	dword ptr [esp+14h],00000000h
  		call	jmp_MSVCRT.dll!??3@YAXPAX@Z
  		mov	ecx,[esp+0Ch]
  		add	esp,00000004h
  		mov	dword ptr [esi],L1000212C
  		pop	esi
  		mov	fs:[00000000h],ecx
  		add	esp,00000010h
  		retn
;------------------------------------------------------------------------------
  		Align	4
 Init_SequencerTick:
  		retn
;------------------------------------------------------------------------------
  		Align	16
 Command:
  		mov	ecx,[ecx+08h]
  		mov	eax,[ecx]
  		push	00000000h
  		push	SSZ100030C4_Arguru_compressor
  		push	SSZ1000309C_By_Arguru__arguru_smartelectroni
  		call	[eax]
  		retn
;------------------------------------------------------------------------------
  		Align	16
 ParameterTweak:
  		mov	eax,[ecx+04h]
  		mov	ecx,[esp+08h]
  		mov	edx,[esp+04h]
  		mov	[eax+edx*4],ecx
  		retn	0008h
;------------------------------------------------------------------------------
  		Align	16
 Work:
;		ecx : Mostly the this pointer, except at the end
; 		ecx+04h = Vals
; 		ecx+08h = pCB
; 		ecx+0Ch = currentGain

;		ebx: psamplesleft pointer
;		ebp:  numsamples
;		eax: used for Vals array and for psamplesleft and right in form or difference (eax=psamplesleft, eax+ecx=psamplesright)
;		esp+10h  (Vals[paramGain]*0.015625000f+1.0f)*0.5		
;		esp+14h = Vals[paramThreshold]
; 		esp+18h = Vals[paramRatio]
; 		esp+1Ch = Vals[paramAttack]
;		esp+20h = Vals[paramRelease]
;		esp+24h = Vals[paramClip]
;
; esp+34h = Vals[paramThreshold]*0.0078125000F

  		sub	esp,00000018h
  		mov	eax,[ecx+04h]
  		fild	dword ptr [eax]
  		mov	edx,[eax+04h]
  		push	ebx
  		mov	ebx,[esp+24h]
  		fmul	dword ptr [0.015625000Float]
  		mov	[esp+08h],edx
  		mov	edx,[eax+0Ch]
  		push	ebp
  		fadd	dword ptr [1.0Float]
  		mov	ebp,[esp+2Ch]
;		test numsamples		
  		test	ebp,ebp
  		mov	[esp+14h],edx
  		mov	edx,[eax+10h]
  		push	esi
  		fmul	qword ptr [0.5Float]
  		push	edi
  		mov	edi,[eax+08h]
  		mov	[esp+20h],edx
  		fstp	dword ptr [esp+10h]
  		mov	edx,[eax+14h]
  		mov	[esp+18h],edi
  		mov	[esp+24h],edx
  		jle	NoSamplesToGain
  		mov	edx,[esp+2Ch]
  		mov	eax,ebx
  		sub	edx,ebx
  		mov	esi,ebp
 ApplyInputGain:
  		fld	dword ptr [esp+10h]
  		add	eax,00000004h
  		dec	esi
  		fmul	dword ptr [edx+eax-04h]
  		fstp	dword ptr [edx+eax-04h]
  		fld	dword ptr [esp+10h]
  		fmul	dword ptr [eax-04h]
  		fstp	dword ptr [eax-04h]
  		jnz	ApplyInputGain
 NoSamplesToGain:
 ; 		test Vals[paramRatio]
  		test	edi,edi
  		jz 	paramRatio_Zero
  		fild	dword ptr [esp+14h]
  		fmul	dword ptr [0.0078125000Float]
  		fstp	dword ptr [esp+34h]
  		fild	dword ptr [esp+18h]
  		fcom	dword ptr [16Float]
  		fnstsw	ax
  		test	ah,01h
  		jnz	Ratiolessthan16
  		fstp	ST(0)
  		fld	dword ptr [0Float]
  		jmp	CalcAttackAndRelease
 Ratiolessthan16:
  		fadd	dword ptr [1.0Float]
  		fdivr	dword ptr [1.0Float]
 CalcAttackAndRelease:
 ;		test numsamples		
 		test	ebp,ebp
  		fild	dword ptr [esp+1Ch]
  		fadd	dword ptr [1.0Float]
  		fmul	qword ptr [44.1Float]
  		fdivr	qword ptr [1.8750000Float]
  		fstp	dword ptr [esp+1Ch]
  		fild	dword ptr [esp+20h]
  		fadd	dword ptr [1.0Float]
  		fmul	qword ptr [44.1Float]
  		fdivr	qword ptr [1.8750000Float]
  		fstp	dword ptr [esp+20h]
  		jle	NothingToCalculate
  		mov	esi,[esp+2Ch]
  		mov	edx,ebx
  		sub	esi,ebx
  		mov	edi,ebp
 CompressLoop:
 ;		input signal
  		fld	dword ptr [edx+esi]
  		fabs
  		fld	dword ptr [edx]
  		fabs
  		fstp	dword ptr [esp+30h]
  		fcom	dword ptr [esp+30h]
  		fnstsw	ax
  		test	ah,41h
  		jz 	LeftBiggerThanRight
  		fstp	ST(0)
  		fld	dword ptr [esp+30h]
 LeftBiggerThanRight:
  		fcom	dword ptr [esp+34h]
  		fnstsw	ax
  		test	ah,41h
  		jnz	ValueSmallerThanThreshold
  		fld	ST(0)
  		fsub	dword ptr [esp+34h]
  		fmul	ST,ST(2)
  		fadd	dword ptr [esp+34h]
  		fdivrp	ST(1),ST
  		jmp	CalculateCurrentGain
 ValueSmallerThanThreshold:
  		fstp	ST(0)
  		fld	dword ptr [1.0Float]
 CalculateCurrentGain:
  		fcom	dword ptr [ecx+0Ch]
  		fsub	dword ptr [ecx+0Ch]
  		fnstsw	ax
  		test	ah,01h
  		jz 	ApplyRelease
		;apply attack
  		fmul	dword ptr [esp+1Ch]
  		jmp	ApplyCurrentGain
 ApplyRelease:
  		fmul	dword ptr [esp+20h]
 ApplyCurrentGain:
  		fadd	dword ptr [ecx+0Ch]
  		add	edx,00000004h
  		dec	edi
  		fstp	dword ptr [ecx+0Ch]
  		fld	dword ptr [edx+esi-04h]
  		fmul	dword ptr [ecx+0Ch]
  		fstp	dword ptr [edx+esi-04h]
  		fld	dword ptr [edx-04h]
  		fmul	dword ptr [ecx+0Ch]
  		fstp	dword ptr [edx-04h]
  		jnz	CompressLoop
 NothingToCalculate:
  		fstp	ST(0)
paramRatio_Zero:
  		mov	eax,[esp+24h]
  		test	eax,eax
  		jz 	NoSoftClip
;		test numsamples		
  		test	ebp,ebp
  		jle	ExitWork
  		mov	edi,[esp+2Ch]
  		mov	esi,ebx
  		sub	edi,ebx
  		mov	[esp+34h],ebp
 ApplySoftClip:
  		fld	dword ptr [esi+edi]
  		call	jmp_MSVCRT.dll!_CItanh
  		fstp	dword ptr [esi+edi]
  		fld	dword ptr [esi]
  		call	jmp_MSVCRT.dll!_CItanh
  		fstp	dword ptr [esi]
  		mov	eax,[esp+34h]
  		add	esi,00000004h
  		dec	eax
  		mov	[esp+34h],eax
  		jnz	ApplySoftClip
 NoSoftClip:
;		test numsamples		
  		test	ebp,ebp
  		jle	ExitWork
  		mov	ecx,[esp+2Ch]
  		mov	eax,ebx
  		sub	ecx,ebx
 Gain32768:
  		fld	dword ptr [eax+ecx]
  		add	eax,00000004h
  		dec	ebp
  		fmul	qword ptr [32768.0Float]
  		fstp	dword ptr [eax+ecx-04h]
  		fld	dword ptr [eax-04h]
  		fmul	qword ptr [32768.0Float]
  		fstp	dword ptr [eax-04h]
  		jnz	Gain32768
 ExitWork:
  		pop	edi
  		pop	esi
  		pop	ebp
  		pop	ebx
  		add	esp,00000018h
  		retn	0010h
;------------------------------------------------------------------------------
  		Align	16
 DescribeValue0:
  		mov	eax,[esp+08h]
  		test	eax,eax
  		jnz	DescribeValue1
  		fild	dword ptr [esp+0Ch]
  		mov	eax,[esp+04h]
  		sub	esp,00000008h
  		fmul	dword ptr [0.015625000Float]
  		fadd	qword ptr [1.8750000Float]
  		fldlg2
  		fxch	ST(1)
  		fyl2x
  		fmul	qword ptr [20.0Float]
  		fstp	qword ptr [esp]
  		push	SSZ1000311C____1f_dB
  		push	eax
  		call	[MSVCRT.dll!sprintf]
  		add	esp,00000010h
  		mov	al,01h
  		retn	000Ch
;------------------------------------------------------------------------------
 DescribeValue1:
  		cmp	eax,00000001h
  		jnz	DescribeValue2
  		mov	eax,[esp+0Ch]
  		test	eax,eax
  		jz 	DescribeValue1inf
  		fild	dword ptr [esp+0Ch]
  		mov	ecx,[esp+04h]
  		sub	esp,00000008h
  		fmul	dword ptr [0.0078125000Float]
  		fldlg2
  		fxch	ST(1)
  		fyl2x
  		fmul	qword ptr [20.0Float]
  		fstp	qword ptr [esp]
  		push	SSZ10003114___1f_dB
  		push	ecx
  		call	[MSVCRT.dll!sprintf]
  		add	esp,00000010h
  		mov	al,01h
  		retn	000Ch
;------------------------------------------------------------------------------
 DescribeValue1inf:
  		mov	edx,[esp+04h]
  		push	SSZ10003108__inf__dB
  		push	edx
  		call	[MSVCRT.dll!sprintf]
  		add	esp,00000008h
  		mov	al,01h
  		retn	000Ch
;------------------------------------------------------------------------------
 DescribeValue2:
  		cmp	eax,00000002h
  		jnz	DescribeValue5
  		push	ebx
  		mov	ebx,[esp+10h]
  		cmp	ebx,00000010h
  		push	esi
  		push	edi
  		jge	DescriveValue2Limiter
  		mov	esi,[esp+10h]
  		mov	edi,[MSVCRT.dll!sprintf]
  		lea	eax,[ebx+01h]
  		push	eax
  		push	SSZ10003100_1__d
  		push	esi
  		call	edi
  		add	esp,0000000Ch
  		jmp	DescribeValue2bypass
 DescriveValue2Limiter:
  		mov	esi,[esp+10h]
  		mov	edi,[MSVCRT.dll!sprintf]
  		push	SSZ100030F8_Limiter
  		push	esi
  		call	edi
  		add	esp,00000008h
 DescribeValue2bypass:
  		test	ebx,ebx
  		jnz	DescribeValue2Other
  		push	SSZ100030E8_1_1__Bypass_
  		push	esi
  		call	edi
  		add	esp,00000008h
 DescribeValue2Other:
  		pop	edi
  		pop	esi
  		mov	al,01h
  		pop	ebx
  		retn	000Ch
;------------------------------------------------------------------------------
 DescribeValue5:
  		cmp	eax,00000003h
  		jz 	DescribeValue34
  		cmp	eax,00000004h
  		jz 	DescribeValue34
  		cmp	eax,00000005h
  		jnz	DescribeInvalidValue
  		mov	eax,[esp+0Ch]
  		test	eax,eax
  		jz 	DescribeValue5off
  		mov	ecx,[esp+04h]
  		push	SSZ100030E4_On
  		push	ecx
  		call	[MSVCRT.dll!sprintf]
  		add	esp,00000008h
  		mov	al,01h
  		retn	000Ch
;------------------------------------------------------------------------------
 DescribeValue5off:
  		mov	edx,[esp+04h]
  		push	SSZ100030E0_Off
  		push	edx
  		call	[MSVCRT.dll!sprintf]
  		add	esp,00000008h
  		mov	al,01h
  		retn	000Ch
;------------------------------------------------------------------------------
 DescribeInvalidValue:
  		xor	al,al
  		retn	000Ch
;------------------------------------------------------------------------------
 DescribeValue34:
  		mov	eax,[esp+0Ch]
  		mov	ecx,[esp+04h]
  		push	eax
  		push	SSZ100030D8__d_ms_
  		push	ecx
  		call	[MSVCRT.dll!sprintf]
  		add	esp,0000000Ch
  		mov	al,01h
  		retn	000Ch
;------------------------------------------------------------------------------
  		Align	8
 L100014A0:
  		mov	dword ptr [ecx],L1000212C
  		retn
;------------------------------------------------------------------------------
  		Align	16
 Return8:
  		retn	0008h
;------------------------------------------------------------------------------
  		Align	16
 Return16:
  		retn	0010h
;------------------------------------------------------------------------------
  		Align	16
 Stop:
  		retn
;------------------------------------------------------------------------------
  		Align	16
 GetDataSize:
  		xor	eax,eax
  		retn
;------------------------------------------------------------------------------
  		Align	16
 IsTrackMuted:
  		db	'2€‚',04h,0
  		Align	16
 MidiNote:
  		retn	000Ch
;------------------------------------------------------------------------------
  		Align	16
 PutGetAndOther:
  		retn	0004h
;------------------------------------------------------------------------------
  		Align	16
 PlayWave:
  		db	'2€‚',0Ch,0
  		Align	16
 SeqTick:
  		retn	0014h
;------------------------------------------------------------------------------
  		Align	16
 L10001540:
  		test	byte ptr [esp+04h],01h
  		push	esi
  		mov	esi,ecx
  		mov	dword ptr [esi],L1000212C
  		jz 	L10001559
  		push	esi
  		call	jmp_MSVCRT.dll!??3@YAXPAX@Z
  		add	esp,00000004h
 L10001559:
  		mov	eax,esi
  		pop	esi
  		retn	0004h
;------------------------------------------------------------------------------
  		Align	4
 jmp_MSVCRT.dll!??2@YAPAXI@Z:
  		jmp	[MSVCRT.dll!??2@YAPAXI@Z]
 jmp_MSVCRT.dll!__CxxFrameHandler:
  		jmp	[MSVCRT.dll!__CxxFrameHandler]
  		Align	8
 jmp_MSVCRT.dll!??3@YAXPAX@Z:
  		jmp	[MSVCRT.dll!??3@YAXPAX@Z]
 jmp_MSVCRT.dll!_CItanh:
  		jmp	[MSVCRT.dll!_CItanh]
 SUB_L1000157C:
  		mov	eax,[esp+08h]
  		test	eax,eax
  		jnz	L10001592
  		cmp	[L10003130],eax
  		jle	L100015BA
  		dec	[L10003130]
 L10001592:
  		mov	ecx,[MSVCRT.dll!_adjust_fdiv]
  		cmp	eax,00000001h
  		mov	ecx,[ecx]
  		mov	[L10003134],ecx
  		jnz	L100015E4
  		push	00000080h
  		call	[MSVCRT.dll!malloc]
  		test	eax,eax
  		pop	ecx
  		mov	[L1000313C],eax
  		jnz	L100015BE
 L100015BA:
  		xor	eax,eax
  		jmp	L10001624
 L100015BE:
  		and	dword ptr [eax],00000000h
  		mov	eax,[L1000313C]
  		push	L10003004
  		push	L10003000
  		mov	[L10003138],eax
  		call	jmp_MSVCRT.dll!_initterm
  		inc	[L10003130]
  		pop	ecx
  		pop	ecx
  		jmp	L10001621
 L100015E4:
  		test	eax,eax
  		jnz	L10001621
  		mov	eax,[L1000313C]
  		test	eax,eax
  		jz 	L10001621
  		mov	ecx,[L10003138]
  		push	esi
  		lea	esi,[ecx-04h]
 L100015FB:
  		cmp	esi,eax
  		jc 	L10001611
  		mov	ecx,[esi]
  		test	ecx,ecx
  		jz 	L1000160C
  		call	ecx
  		mov	eax,[L1000313C]
 L1000160C:
  		sub	esi,00000004h
  		jmp	L100015FB
 L10001611:
  		push	eax
  		call	[MSVCRT.dll!free]
  		and	dword ptr [L1000313C],00000000h
  		pop	ecx
  		pop	esi
 L10001621:
  		push	00000001h
  		pop	eax
 L10001624:
  		retn	000Ch
;------------------------------------------------------------------------------
 EntryPoint:
  		push	ebp
  		mov	ebp,esp
  		push	ebx
  		mov	ebx,[ebp+08h]
  		push	esi
  		mov	esi,[ebp+0Ch]
  		push	edi
  		mov	edi,[ebp+10h]
  		test	esi,esi
  		jnz	L10001643
  		cmp	dword ptr [L10003130],00000000h
  		jmp	L10001669
 L10001643:
  		cmp	esi,00000001h
  		jz 	L1000164D
  		cmp	esi,00000002h
  		jnz	L1000166F
 L1000164D:
  		mov	eax,[L10003140]
  		test	eax,eax
  		jz 	L1000165F
  		push	edi
  		push	esi
  		push	ebx
  		call	eax
  		test	eax,eax
  		jz 	L1000166B
 L1000165F:
  		push	edi
  		push	esi
  		push	ebx
  		call	SUB_L1000157C
  		test	eax,eax
 L10001669:
  		jnz	L1000166F
 L1000166B:
  		xor	eax,eax
  		jmp	L100016BD
 L1000166F:
  		push	edi
  		push	esi
  		push	ebx
  		call	SUB_L100016CA
  		cmp	esi,00000001h
  		mov	[ebp+0Ch],eax
  		jnz	L1000168B
  		test	eax,eax
  		jnz	L100016BA
  		push	edi
  		push	eax
  		push	ebx
  		call	SUB_L1000157C
 L1000168B:
  		test	esi,esi
  		jz 	L10001694
  		cmp	esi,00000003h
  		jnz	L100016BA
 L10001694:
  		push	edi
  		push	esi
  		push	ebx
  		call	SUB_L1000157C
  		test	eax,eax
  		jnz	L100016A3
  		and	[ebp+0Ch],eax
 L100016A3:
  		cmp	dword ptr [ebp+0Ch],00000000h
  		jz 	L100016BA
  		mov	eax,[L10003140]
  		test	eax,eax
  		jz 	L100016BA
  		push	edi
  		push	esi
  		push	ebx
  		call	eax
  		mov	[ebp+0Ch],eax
 L100016BA:
  		mov	eax,[ebp+0Ch]
 L100016BD:
  		pop	edi
  		pop	esi
  		pop	ebx
  		pop	ebp
  		retn	000Ch
;------------------------------------------------------------------------------
 jmp_MSVCRT.dll!_initterm:
  		jmp	[MSVCRT.dll!_initterm]
 SUB_L100016CA:
  		cmp	dword ptr [esp+08h],00000001h
  		jnz	L100016E4
  		cmp	dword ptr [L10003140],00000000h
  		jnz	L100016E4
  		push	[esp+04h]
  		call	[KERNEL32.dll!DisableThreadLibraryCalls]
 L100016E4:
  		push	00000001h
  		pop	eax
  		retn	000Ch
;------------------------------------------------------------------------------
  		Align	8
 L100016F0:
  		mov	ecx,[ebp-10h]
  		jmp	L100014A0
 L100016F8:
  		mov	eax,L100021B8
  		jmp	jmp_MSVCRT.dll!__CxxFrameHandler
  		Align	16
 L10001710:
  		mov	ecx,[ebp-10h]
  		jmp	L100014A0
 L10001718:
  		mov	eax,L100021E0
  		jmp	jmp_MSVCRT.dll!__CxxFrameHandler
;------------------------------------------------------------------------------
 		000008DEh DUP (??)
;
;
;------------------------------------------------------------------------------
;  Name: .rdata (Data Section)
;  Virtual Address:    10002000h  Virtual Size:    00000388h
;  Pointer To RawData: 00002000h  Size Of RawData: 00001000h
;
 KERNEL32.dll!DisableThreadLibraryCalls:
  		dd	??
  		dd	00000000
 MSVCRT.dll!??3@YAXPAX@Z:
  		dd	??
 MSVCRT.dll!_CItanh:
  		dd	??
 MSVCRT.dll!sprintf:
  		dd	??
 MSVCRT.dll!free:
  		dd	??
 MSVCRT.dll!__CxxFrameHandler:
  		dd	??
 MSVCRT.dll!malloc:
  		dd	??
 MSVCRT.dll!_adjust_fdiv:
  		dd	??
 MSVCRT.dll!_initterm:
  		dd	??
 MSVCRT.dll!??2@YAPAXI@Z:
  		dd	??
  		dd	00000000
 ParamInputGain:
 		dd	SSZ10003090_Input_gain
 		dd	SSZ10003090_Input_gain
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	80h;   '?'
 		db	00h;
 		db	00h;
 		db	00h;
 		db	02h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 ParamThreshold:
 		dd	SSZ10003084_Threshold
 		dd	SSZ10003084_Threshold
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	80h;   '?'
 		db	00h;
 		db	00h;
 		db	00h;
 		db	02h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	40h;   '@'
 		db	00h;
 		db	00h;
 		db	00h;
 ParamRatio:
 		dd	SSZ1000307C_Ratio
 		dd	SSZ1000307C_Ratio
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	10h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	02h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	10h;
 		db	00h;
 		db	00h;
 		db	00h;
 ParamAttack:
 		dd	SSZ10003074_Attack
 		dd	SSZ10003074_Attack
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	80h;   '?'
 		db	00h;
 		db	00h;
 		db	00h;
 		db	02h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	06h;
 		db	00h;
 		db	00h;
 		db	00h;
 ParamRelease:
 		dd	SSZ1000306C_Release
 		dd	SSZ1000306C_Release
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	80h;   '?'
 		db	00h;
 		db	00h;
 		db	00h;
 		db	02h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	2Ch;   ','
 		db	00h;
 		db	00h;
 		db	00h;
 ParamSoftClip:
 		dd	SSZ10003060_Soft_clip
 		dd	SSZ10003060_Soft_clip
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	01h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	02h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 CMachineInfo:
 		db	0Bh;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	06h;
 		db	00h;
 		db	00h;
 		db	00h;
 		dd	PD10003048pParameters
 		dd	SSZ10003034_Arguru_Compressor
 		dd	SSZ10003028_Compressor
 		dd	SSZ10003018_J__Arguelles
 		dd	SSZ10003010_About
 		db	01h;
 		db	00h;
 		db	00h;
 		db	00h;
 CMachineInterface:
 		dd	MachineDestructor
 		dd	Init_SequencerTick
 		dd	Init_SequencerTick
 		dd	ParameterTweak
 		dd	Work
 		dd	Stop
 		dd	PutGetAndOther
 		dd	PutGetAndOther
 		dd	GetDataSize
 		dd	Command
 		dd	PutGetAndOther
 		dd	IsTrackMuted
 		dd	MidiNote
 		dd	PutGetAndOther
 		dd	DescribeValue0
 		dd	PlayWave
 		dd	SeqTick
 		dd	Stop
 L1000212C:
 		dd	L10001540
 		dd	Stop
 		dd	Stop
 		dd	Return8
 		dd	Return16
 		dd	Stop
 		dd	PutGetAndOther
 		dd	PutGetAndOther
 		dd	GetDataSize
 		dd	Stop
 		dd	PutGetAndOther
 		dd	IsTrackMuted
 		dd	MidiNote
 		dd	PutGetAndOther
 		dd	PlayWave
 		dd	PlayWave
 		dd	SeqTick
 		dd	Stop
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 32768.0Float:
  		dq	40E0000000000000h
 1.8750000Float:
  		dq	3FF0000000000000h
 44.1Float:
  		dq	40460CCCCCCCCCCDh
 0Float:
  		dd	00000000h
 16Float:
  		dd	41800000h
 0.0078125000Float:
  		dd	3C000000h
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 0.5Float:
  		dq	3F00000000000000h
 1.0Float:
  		dd	3F800000h
 0.015625000Float:
  		dd	3C800000h
 20.0Float:
  		dq	4034000000000000h
 L100021B8:
  		dd	19930520h
  		dd	00000001h
  		dd	L100021D8
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
 L100021D8:
  		dd	FFFFFFFFh
  		dd	L100016F0
 L100021E0:
  		dd	19930520h
  		dd	00000001h
  		dd	L10002200
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
 L10002200:
  		dd	FFFFFFFFh
  		dd	L10001710
  		dd	0000224Ch
  		dd	00000000h
  		dd	00000000h
  		dd	000022BCh
  		dd	00002008h
  		dd	00002244h
  		dd	00000000h
  		dd	00000000h
  		dd	00002312h
  		dd	00002000h
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
  		dd	00000000h
  		dd	000022F6h
  		dd	00000000h
  		dd	00002298h
  		dd	000022A8h
  		dd	000022B2h
  		dd	000022C8h
  		dd	00002284h
  		dd	000022DCh
  		dd	000022E6h
  		dd	000022D0h
  		dd	00002274h
  		dd	00000000h
  		dw	000Fh
  		db	'??2@YAPAXI@Z',0
  		db	00h
  		dw	0049h
  		db	'__CxxFrameHandler',0
  		dw	0010h
  		db	'??3@YAXPAX@Z',0
  		db	00h
  		dw	0040h
  		db	'_CItanh',0
  		dw	02B2h
  		db	'sprintf',0
  		db	'MSVCRT.dll',0
  		db	00h
  		dw	025Eh
  		db	'free',0
  		db	00h
  		dw	010Fh
  		db	'_initterm',0
  		dw	0291h
  		db	'malloc',0
  		db	00h
  		dw	009Dh
  		db	'_adjust_fdiv',0
  		db	00h
  		dw	005Dh
  		db	'DisableThreadLibraryCalls',0
  		db	'KERNEL32.dll',0
  		db	00h
  		dd	00000000h
  		dd	3CADF0F7h
  		dw	0000h
  		dw	0000h
  		dd	0000235Ch
  		dd	00000001h
  		dd	00000002h
  		dd	00000002h
  		dd	00002348h
  		dd	00002350h
  		dd	00002358h
  		dd	00001010h
  		dd	00001000h
  		dd	00002372h
  		dd	00002380h
  		dw	0000h
  		dw	0001h
  		db	'arguru_compressor.dll',0
  		db	'CreateMachine',0
  		db	'GetInfo',0
;------------------------------------------------------------------------------
 		00000C78h DUP (??)
;
;
;------------------------------------------------------------------------------
;  Name: .data
;  Virtual Address:    10003000h  Virtual Size:    00000144h
;  Pointer To RawData: 00003000h  Size Of RawData: 00001000h
;
 L10003000:
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 L10003004:
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 SSZ10003010_About:
  		db	'About',0
  		Align	4
 SSZ10003018_J__Arguelles:
  		db	'J. Arguelles',0
  		Align	4
 SSZ10003028_Compressor:
  		db	'Compressor',0
  		Align	4
 SSZ10003034_Arguru_Compressor:
  		db	'Arguru Compressor',0
  		Align	4
 PD10003048pParameters:
 		dd	ParamInputGain
 		dd	ParamThreshold
 		dd	ParamRatio
 		dd	ParamAttack
 		dd	ParamRelease
 		dd	ParamSoftClip
 SSZ10003060_Soft_clip:
  		db	'Soft clip',0
  		Align	4
 SSZ1000306C_Release:
  		db	'Release',0
 SSZ10003074_Attack:
  		db	'Attack',0
  		Align	4
 SSZ1000307C_Ratio:
  		db	'Ratio',0
  		Align	4
 SSZ10003084_Threshold:
  		db	'Threshold',0
  		Align	4
 SSZ10003090_Input_gain:
  		db	'Input gain',0
  		Align	4
 SSZ1000309C_By_Arguru__arguru_smartelectroni:
  		db	'By Arguru <arguru@smartelectronix.com>',0
  		Align	4
 SSZ100030C4_Arguru_compressor:
  		db	'Arguru compressor',0
  		Align	4
 SSZ100030D8__d_ms_:
  		db	'%d ms.',0
  		Align	4
 SSZ100030E0_Off:
  		db	'Off',0
 SSZ100030E4_On:
  		db	'On',0
 		db	00h;
 SSZ100030E8_1_1__Bypass_:
  		db	'1:1 (Bypass)',0
  		Align	4
 SSZ100030F8_Limiter:
  		db	'Limiter',0
 SSZ10003100_1__d:
  		db	'1:%d',0
  		Align	4
 SSZ10003108__inf__dB:
  		db	'-inf. dB',0
  		Align	4
 SSZ10003114___1f_dB:
  		db	'%.1f dB',0
 SSZ1000311C____1f_dB:
  		db	'+%.1f dB',0
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 L10003130:
  		dd	00000000h
 L10003134:
 		db	00h;
 		db	00h;
 		db	00h;
 		db	00h;
 L10003138:
  		dd	00000000h
 L1000313C:
  		dd	00000000h
 L10003140:
  		dd	00000000h
;------------------------------------------------------------------------------
 		00000EBCh DUP (??)
;
;
;------------------------------------------------------------------------------
; Exports
;
 	Index: 1	Name: CreateMachine
 	Index: 2	Name: GetInfo
;
;------------------------------------------------------------------------------
; Imports from MSVCRT.dll
;
 	extrn ??3@YAXPAX@Z
 	extrn _CItanh
 	extrn sprintf
 	extrn free
 	extrn __CxxFrameHandler
 	extrn malloc
 	extrn _adjust_fdiv
 	extrn _initterm
 	extrn ??2@YAPAXI@Z
;
; Imports from KERNEL32.dll
;
 	extrn DisableThreadLibraryCalls
;
;------------------------------------------------------------------------------
