//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Psycle2.rc
//
#define IDCANCEL3                       3
#define IDCANCEL2                       4
#define IDOK3                           5
#define IDD_ABOUTBOX                    100
#define IDD_DIALOGBAR                   103
#define IDD_PSYBAR                      103
#define IDR_MAINFRAME                   128
#define IDR_PSYCLETYPE                  129
#define IDD_WAVEOUTCONFIG               130
#define IDD_GEAR_PSYCHOSC               132
#define IDB_PSYCHOSC                    133
#define IDD_INFO                        134
#define IDD_WIREDIALOG                  135
#define IDD_CONTROLDESK                 136
#define IDD_NEWMACHINE                  137
#define IDD_GEARDISTORT                 138
#define IDB_DIST                        139
#define IDD_MACPROP                     140
#define IDD_PATDLG                      141
#define IDD_INSTRUMENT                  142
#define IDB_PSYCLE                      147
#define IDB_PARENT                      148
#define IDD_GEAR_TRACKER                151
#define IDB_SAMPLER                     152
#define IDD_GEAR_DELAY                  154
#define IDB_DALAYDELAY                  157
#define IDD_ENVDIALOG                   158
#define IDD_RECORDER                    159
#define IDD_PATNAVDIALOG                160
#define IDB_SPEAKER                     161
#define IDD_SAVESONG                    162
#define IDD_GEAR_FILTER                 163
#define IDD_IBROWSE                     164
#define IDD_GREETS                      167
#define IDB_CPU                         169
#define IDD_CONFIG                      176
#define IDD_SONGPROP                    177
#define IDD_GEAR_GAINER                 179
#define IDD_PSYBAR2                     180
#define IDD_GEAR_FLANGER                181
#define IDB_FLANGER                     182
#define IDD_GEAR_PLUGIN                 183
#define IDD_SEQUENCER                   186
#define IDD_MASTERDLG                   187
#define IDB_VOLARROW                    188
#define IDR_WAVEFRAME                   189
#define IDR_MACHINEFRAME                193
#define IDB_KNOB                        195
#define IDD_NEWVAL                      197
#define IDD_VSTHOST_DIALOG              199
#define IDD_VSTRACK                     200
#define IDB_STEINBERGVST                201
#define IDR_VSTFRAME                    202
#define IDD_GEARVST                     204
#define IDB_STUFF                       205
#define IDD_DSOUNDCONFIG                208
#define IDB_DIRECTX                     210
#define IDD_OUTPUT                      211
#define IDC_CONFIG_DEVICE               1000
#define IDC_SLIDER1                     1000
#define IDC_CONFIG_SAMPLERATE           1001
#define IDC_SLIDER2                     1001
#define IDC_CONFIG_BUFNUM               1002
#define IDC_SLIDER3                     1002
#define IDC_CONFIG_BUFSIZE              1003
#define IDC_SLIDER4                     1003
#define IDC_TEXT1                       1003
#define IDC_CONFIG_DITHER               1004
#define IDC_F_SLIDER1                   1004
#define IDC_SLIDER5                     1004
#define IDC_CONFIG_BUFNUM_SPIN          1005
#define IDC_STATIC1                     1005
#define IDC_F_SLIDER2                   1005
#define IDC_SLIDER6                     1005
#define IDC_CONFIG_BUFSIZE_SPIN         1006
#define IDC_STATIC2                     1006
#define IDC_F_SLIDER3                   1006
#define IDC_COMBO2                      1006
#define IDC_CONFIG_LATENCY              1007
#define IDC_STATIC3                     1007
#define IDC_F_SLIDER4                   1007
#define IDC_STATIC4                     1008
#define IDC_SLIDER9                     1008
#define IDC_SLIDER10                    1009
#define IDC_MACHINELIST                 1010
#define IDC_BUTTON1                     1011
#define IDC_BUTTON3                     1012
#define IDC_ENVELOPE                    1012
#define IDC_EDIT1                       1013
#define IDC_BUTTON14                    1013
#define IDC_TREE1                       1014
#define IDC_BUTTON15                    1014
#define IDC_EDIT3                       1014
#define IDC_NAMELABEL                   1015
#define IDC_BUTTON9                     1015
#define IDC_BUTTON16                    1015
#define IDC_EDIT4                       1015
#define IDC_DESCLABEL                   1016
#define IDC_INSTEDIT                    1016
#define IDC_BUTTON17                    1016
#define IDC_VERLABEL                    1017
#define IDC_BUTTON11                    1017
#define IDC_BUTTON2                     1018
#define IDC_BUTTON18                    1018
#define IDC_BUTTON4                     1019
#define IDC_BUTTON19                    1019
#define IDC_BUTTON5                     1020
#define IDC_BUTTON20                    1020
#define IDC_CHECK1                      1021
#define IDC_BUTTON6                     1021
#define IDC_BUTTON21                    1021
#define IDC_BUTTON12                    1022
#define IDC_BUTTON22                    1022
#define IDC_CHECK2                      1022
#define IDC_BUTTON13                    1023
#define IDC_CHECK3                      1023
#define IDC_TPBLABEL                    1024
#define IDC_BUTTON23                    1024
#define IDC_BPMLABEL                    1025
#define IDC_BUTTON24                    1025
#define IDC_INSTCOMBO                   1026
#define IDC_LOOPOFF                     1026
#define IDC_PBAR_LS                     1026
#define IDC_BUTTON25                    1026
#define IDC_INSTINDEX                   1027
#define IDC_EDIT2                       1027
#define IDC_LOOPFORWARD                 1027
#define IDC_PBAR_LE                     1027
#define IDC_BUTTON26                    1027
#define IDC_SPIN1                       1028
#define IDC_LOOPBOUNCE                  1028
#define IDC_PBAR_LEN                    1028
#define IDC_LAYER1                      1030
#define IDC_LAYER2                      1031
#define IDC_LAYER3                      1032
#define IDC_LAYER4                      1033
#define IDC_LAYER5                      1034
#define IDC_LAYER6                      1035
#define IDC_LAYER7                      1036
#define IDC_LAYER8                      1037
#define IDC_LAYER9                      1038
#define IDC_LAYER10                     1039
#define IDC_LAYER11                     1040
#define IDC_LAYER12                     1041
#define IDC_LAYER13                     1042
#define IDC_LAYER14                     1043
#define IDC_LAYER15                     1044
#define IDC_LAYER16                     1045
#define IDC_LIST2                       1046
#define IDC_LAYERN                      1047
#define IDC_WAVENAME                    1048
#define IDC_INSTNUMBER                  1049
#define IDC_DIRECTORY                   1050
#define IDC_DIRUPDATE                   1051
#define IDC_LOOPCONT                    1052
#define IDC_LOOPSTART                   1053
#define IDC_LOOPEND                     1054
#define IDC_STATUS                      1055
#define IDC_STEREO                      1056
#define IDC_LOOPTYPE                    1057
#define IDC_WAVELENGTH                  1058
#define IDC_VOLABEL                     1059
#define IDC_BUTTON7                     1060
#define IDC_INSTNAME                    1061
#define IDC_VOLABEL2                    1062
#define IDC_BUTTON10                    1066
#define IDC_PROGRESS1                   1067
#define IDC_COMBO1                      1068
#define IDC_BUTTON8                     1071
#define IDC_NNA_COMBO                   1072
#define IDC_VK_1                        1081
#define IDC_TRACKLABEL                  1082
#define IDC_TRACKSLIDER                 1083
#define IDC_TRACKLABEL2                 1084
#define IDC_TRACKSLIDER2                1085
#define IDC_SLIDER_TIME                 1089
#define IDC_LABEL_LTIME                 1090
#define IDC_SLIDER_TIME2                1091
#define IDC_LABEL_LTIME2                1092
#define IDC_F_LABEL_L                   1093
#define IDC_F_LABEL_R                   1094
#define IDC_LABEL_MSL                   1095
#define IDC_AMPFRAME                    1095
#define IDC_A_A_LABEL                   1096
#define IDC_DRYLABEL                    1096
#define IDC_LABEL_MSR                   1097
#define IDC_A_D_LABEL                   1097
#define IDC_A_R_LABEL                   1098
#define IDC_WETLABEL                    1098
#define IDC_A_S_LABEL                   1099
#define IDC_AMPFRAME2                   1100
#define IDC_F_A_LABEL                   1101
#define IDC_F_D_LABEL                   1102
#define IDC_F_R_LABEL                   1103
#define IDC_F_S_LABEL                   1104
#define IDC_CUTOFF_LBL                  1105
#define IDC_LABELQ                      1106
#define IDC_A_A_LABEL7                  1109
#define IDC_LIST1                       1109
#define IDC_PNLABEL                     1110
#define IDC_CREATEB                     1111
#define IDC_CHECKFN                     1120
#define IDC_DRYSLIDER                   1121
#define IDC_WETSLIDER                   1122
#define IDC_RPAN                        1125
#define IDC_RCUT                        1126
#define IDC_PANSLIDER                   1127
#define IDC_RRES                        1128
#define IDC_CPUIDLE_LABEL               1128
#define IDC_CPUL                        1129
#define IDC_MCPULABEL                   1130
#define IDC_MCPULABEL2                  1131
#define IDC_CHECK_LP                    1132
#define IDC_MEM_RESO                    1132
#define IDC_MEM_RESO2                   1133
#define IDC_MEM_RESO3                   1134
#define IDC_BROWSE_MV                   1135
#define IDC_MEM_RESO4                   1135
#define IDC_BROWSE_PV                   1136
#define IDC_BROWSE_SV                   1137
#define IDC_LVUM                        1139
#define IDC_RVUM                        1140
#define IDC_SSCOMBO                     1141
#define IDC_LABEL1                      1142
#define IDC_SSCOMBO2                    1142
#define IDC_LABEL2                      1143
#define IDC_TRACKCOMBO                  1143
#define IDC_LABEL3                      1144
#define IDC_BAR_COMBOGEN                1144
#define IDC_LABEL4                      1145
#define IDC_BAR_COMBOINS                1145
#define IDC_LABEL5                      1146
#define IDC_LABEL6                      1147
#define IDC_PRESETCOMBO                 1148
#define IDC_PLUGLABEL                   1149
#define IDC_DISPLAY                     1150
#define IDC_SHORTPAR                    1151
#define IDC_PLUGLABEL2                  1152
#define IDC_PARLIST                     1153
#define IDC_FRAMECLIP                   1154
#define IDC_CLIPBUT                     1155
#define IDC_B_POSADD                    1156
#define IDC_B_POSDEC                    1157
#define IDC_B_POSADD2                   1158
#define IDC_B_POSDEC2                   1159
#define IDC_B_LENADD                    1160
#define IDC_SEQVIEW                     1160
#define IDC_B_LENDEC                    1161
#define IDC_DBLEVEL                     1161
#define IDC_LOADWAVE                    1162
#define IDC_EDITWAVE                    1163
#define IDC_WAVEBUT                     1164
#define IDC_B_DECGEN                    1165
#define IDC_B_INCGEN                    1166
#define IDC_B_DECWAV                    1167
#define IDC_B_INCWAV                    1168
#define IDC_CHECK4                      1169
#define IDC_LOOPEDIT                    1170
#define IDC_SEQLIST                     1171
#define IDC_INCSHORT                    1172
#define IDC_DECSHORT                    1173
#define IDC_SEQINS                      1174
#define IDC_SEQDEL                      1175
#define IDC_SEQCLR                      1176
#define IDC_SEQSPR                      1177
#define IDC_SEQ1                        1178
#define IDC_SEQ2                        1179
#define IDC_SEQ3                        1180
#define IDC_INCPOS2                     1181
#define IDC_DECPOS2                     1182
#define IDC_DECPAT2                     1183
#define IDC_INCPAT2                     1184
#define IDC_DECLEN                      1185
#define IDC_INCLEN                      1186
#define IDC_SEQSLEN                     1187
#define IDC_DSOUND_DEVICE               1187
#define IDC_DSOUND_BUFNUM_EDIT          1188
#define IDC_DSOUND_BUFSIZE_SPIN         1189
#define IDC_DSOUND_BUFSIZE_EDIT         1190
#define IDC_DSOUND_BUFNUM_SPIN          1191
#define IDC_DSOUND_LATENCY              1192
#define IDC_DSOUND_SAMPLERATE_COMBO     1193
#define IDC_DSOUND_DITHER               1194
#define IDC_DRIVER                      1196
#define IDC_CONFIG                      1197
#define IDC_EXCLUSIVE                   1198
#define ID_CONFIGURATION_AUDIODRIVER    32771
#define ID_CONFIGURATION_FREEAUDIO      32772
#define ID_HELP_PSYCLEENVIROMENTINFO    32773
#define ID_SEQTOOL                      32774
#define ID_BUTTON32775                  32775
#define ID_MACHINEVIEW                  32776
#define IDM_CONTROLDESK                 32777
#define IDT_CONTROLDESK                 32778
#define ID_VIEW_INSTRUMENTEDITOR        32779
#define ID_ABOUTPSYCLE                  32780
#define ID_DIALOGBAR                    32781
#define ID_BARPLAY                      32785
#define ID_BARSTOP                      32786
#define ID_BUTTON32790                  32790
#define ID_BUTTON32791                  32791
#define ID_BARPLAYB                     32792
#define ID_SHOWIED                      32793
#define ID_RECORDB                      32794
#define ID_FILE_LOADSONG                32795
#define ID_FILE_SAVESONG                32796
#define ID_CPU_PSYCLEPERFOMANCEMONITOR  32797
#define ID_HELP_SALUDOS                 32798
#define ID_COPYPATTERN                  32799
#define ID_CUTPATTERN                   32800
#define ID_PASTEPATTERN                 32801
#define ID_PPLAY                        32806
#define ID_CONFIGURATION_SETTINGS_BACKGROUNDSKIN 32808
#define ID_FILE_SONGPROPERTIES          32809
#define ID_BUTTON32810                  32810
#define ID_SHOWPSEQ                     32811
#define ID_NEWMACHINE                   32817
#define ID_PSYHELP                      32818
#define ID_SELECCION_ZOOM               32819
#define ID_SELECTION_FADEIN             32820
#define ID_SELECTION_FADEOUT            32821
#define ID_CUTWAVE                      32822
#define ID_SELECCION_ZOOMOUT            32823
#define ID_PATTERNVIEW                  32824
#define ID_PARAMETERS_RANDOMPARAMETERS  32825
#define ID_PARAMETERS_RESETPARAMETERS   32826
#define ID_PARAMETERS_COMMAND           32827
#define ID_PARAMETERS_LOADPRESET        32828
#define ID_PRESET_SAVEPRESET            32829
#define ID_MACHINE_ABOUTTHISMACHINE     32830
#define ID_MACHINE_ABOUTPSYGEARV10      32831
#define ID_CONFIGURATION_KEYBOARDLAYOUT 32834
#define ID_CONFIGURATION_KEYBOARDLAYOUT_STANDARD 32835
#define ID_CONFIGURATION_KEYBOARDLAYOUT_FRENCH 32836
#define ID_VST2MANAGER_VST2PLUGINMANAGER 32837

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1199
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
