######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 12 12:29:17 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += mainwindow.cpp qpsycle.cpp
RESOURCES += qpsycle.qrc
