#! /usr/bin/env sh

##############################################################################
#
# This program is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2 of the License, or (at your option) any later version.
# copyright 2004-2007 johan boule <bohan@jabber.org>
# copyright 2004-2007 psycledelics http://psycle.sourceforge.net
#
##############################################################################

update_date()
{
	local page=$1 &&
	local tag=$2 &&
	local file=$3 &&
	local date=$(date --universal +"%Z %Y %B %d %A %T" --reference=$file) &&
	sed -i "s/<\!-- date $tag -->.*$/<\!-- date $tag --> $date/" $page &&
	chmod ug=rw,o=r $page
} &&

main
{
	local page=$1 &&
	local tag=$2 &&
	local file=$3 &&
	cd $(dirname $0) &&
	if test -n "$file"
	then
		update_date $page $tag $file "by $(id --user --name)"
	else
		update_date index.xml bin packages/microsoft/psycle.bin.7z
		update_date index.xml bin.mfc packages/microsoft/psycle.mfc.bin.zip
#		update_date index.xml bin.mfc.release-candidate packages/microsoft/psycle.mfc.bin.release_candidate.7z
		update_date index.xml bin.mfc.release-candidate packages/microsoft/psycle.mfc.bin.release_1_8_bugfixes.tar.gz
	fi
} &&

main "$@"
