#! /usr/bin/env bash

function main {
	cd "$(dirname $0)" &&
	qmake -recursive CONFIG-=debug CONFIG-=debug_and_release &&
	mingw32-make &&
	(cd ../psycle-plugins && scons) &&
	local install_dir=++install &&
	rm -Rf $install_dir &&
	mkdir -p $install_dir/bin &&
	cp -f \
		{.,../psycle-{core,audiodrivers}/++build/*.{dll,exe} \
		../psycle-plugins/++packageneric/variants/default/stage-install/usr/local/bin/*.dll \
		$install_dir/bin &&
	local tar_name=qpsycle &&
	../packageneric/generic/microsoft-dll-collector $install_dir $tar_name &&
	echo subversion revision "$(svnversion)" > $install_dir/$tar_name/version.text &&
	tar cvjf $install_dir/$tar_name.tar.bz2 --directory=$install_dir $tar_name &&
	ls -lh $install_dir/$tar_name.tar.bz2 &&
	#(cd $install_dir && 7za a -ms=on -mx=9 -m0=BCJ2 -m1=LZMA -m2=LZMA -m3=LZMA -mb0:1 -mb0s1:2 -mb0s2:3 $tar_name.7z $tar_name) &&
	#ls -lh $install_dir/$tar_name.7z &&
	true
} &&

main "$@"
