#! /usr/bin/env scons

# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2006-2007 johan boule <bohan@jabber.org>
# copyright 2006-2007 psycledelics http://psycle.pastnotecut.org

# To be able to import the packageneric package, we add the parent dir of this SConstruct file to the python path:
import sys, os ; sys.path.append(os.path.split(os.getcwd())[0]) # SCons always makes the dir of the SConstruct file the current dir.

# project

from packageneric.generic.scons.project import project
project = project(name = 'psycle-helpers')

# source package

from packageneric.generic.scons.source_package import source_package
from packageneric.generic.scons.version import version
source_package = source_package(project,
	name = project.name(),
	version = version(1, 9),
	description = 'helper routines for psycle',
	long_description = \
		"these are the some helper routines for psycle."
		"psycle is a modular music creation studio."
)

source_package.add_files(['README', 'NEWS', 'ChangeLog', 'AUTHORS', 'COPYING', 'TODO'])

# external packages

from packageneric.generic.scons.check.external_package import external_package as external_package_check
from packageneric.generic.scons.check.pkg_config import pkg_config as pkg_config_check
from packageneric.generic.scons.check.cxx_build import cxx_build as cxx_build_check

import os.path
universalis = os.path.join(os.pardir, 'universalis', 'SConstruct')
if os.path.exists(universalis): universalis = project.subscript(universalis).local_package()
else:
	universalis = external_package_check(project, name = 'universalis',
		url = 'http://psycle.sourceforge.net',
		distribution_packages = {
			'zero-install': 'http://psycle.sourceforge.net/packages/0install/interfaces/universalis-dev.xml',
			'debian and ubuntu': 'lib-universalis-dev (>= 0)',
			'gentoo': '...',
			'fedora': '...',
			'cygwin': '...'
		},
		dependencies = [pkg_config_check(project, name = 'universalis >= 0')]
	)

# modules

from packageneric.generic.scons.module import module

# pkg-config packages

from packageneric.generic.scons.pkg_config_package import pkg_config_package
pkg_config_package = pkg_config_package(project,
	name = source_package.name(),
	version = source_package.version(),
	description = source_package.description(),
	dependencies = [universalis],
	modules = []
)
pkg_config_package.uninstalled_env().compilers().cxx().paths().add(['src'])

# unit tests

from packageneric.pool.boost import boost
boost_test = boost(project, 103300, ['unit_test_framework'])

unit_test_module = module(source_package,
			name = source_package.name() + '_unit_tests',
			version = source_package.version(),
			dependencies = [pkg_config_package.local_package(), universalis, boost_test], # todo universalis should be a brought by pkg_config_package
			target_type = module.target_types.program
)
unit_test_module.contexes().source().compilers().cxx().paths().add(['src'])
from packageneric.generic.scons.find import find
unit_test_module.add_sources(find(project, 'src', [os.path.join(os.curdir, 'unit_tests.cpp')]))

###
project.default_targets([pkg_config_package, unit_test_module])
Return('pkg_config_package')
