#! /usr/bin/env python

import sys

def do_one_file(path):
	f = file(path, 'r')
	lines = f.readlines()
	f.close()
	chars = []
	replaced = False
	for line in lines:
		for char in line:
			if char != '\r': chars.append(char)
			else: replaced = True
	if replaced:
		f = file(path, 'w')
		for char in chars: f.write(char)
		f.close()
		print 'removed carriage return characters in', path

if __name__ == '__main__':
	for path in sys.argv[1:]:
		do_one_file(path)
