#! /usr/bin/env python

import sys

def do_one_file(path):
	f = file(path, 'r')
	lines = f.readlines()
	f.close()
	chars = []
	tab_found = False
	for line in lines:
		indentation = True
		for char in line:
			if indentation:
				if char == '\t':
					tab_found = True
					chars.append(' ' * 2)
					continue
				elif char != ' ':
					indentation = False
			chars.append(char)
	if tab_found:
		print sys.argv[0] + ':', 'found indentation tabs in file', path, '; replacing ...'
		f = file(path, 'w')
		for char in chars:
			f.write(char)
		f.close()

if __name__ == '__main__':
	for path in sys.argv[1:]:
		do_one_file(path)
