#! /usr/bin/env scons

# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2006 johan boule <bohan@jabber.org>
# copyright 2006 psycledelics http://psycle.pastnotecut.org

# To be able to import the packageneric package, we add the parent dir of this SConstruct file to the python path:
import sys, os, os.path
sys.path.append(os.path.split(os.getcwd())[0]) # SCons always makes the dir of the SConstruct file the current dir.

# project

from packageneric.generic.scons.project import project
project = project(name = 'xpsycle')

# authors/maintainers/uploaders

from packageneric.generic.scons.person import person
prodos = person('Stefan NattKemper', 'natti__@user.sourceforge.net')
bohan = person('Johan Boule', 'bohan.packageneric@retropaganda.info')

# source package

from packageneric.generic.scons.source_package import source_package
from packageneric.generic.scons.version import version
source_package = source_package(project,
	name = 'xpsycle',
	version = version(0, 0),
	description = 'ngrs graphic toolkit library',
	long_description = """\
psycle is a modular music creation studio ...
"""
)

# external packages

from packageneric.generic.scons.check.external_package import external_package as external_package_check
from packageneric.generic.scons.check.pkg_config import pkg_config as pkg_config_check
from packageneric.generic.scons.check.cxx_build import cxx_build as cxx_build_check

ngrs = os.path.join('..', 'ngrs', 'SConstruct')
if os.path.exists(ngrs): ngrs = project.subscript(ngrs).local_package()
else:
	ngrs = external_package_check(project, name = 'ngrs',
		dependencies = [
			pkg_config_check(project, name = 'ngrs-0 >= 0')
		],
		distribution_packages = {
			'debian and ubuntu': 'lib-ngrs-0-dev (>= 0)',
			'gentoo': '...',
			'fedora': '...',
			'cygwin': '...'
		},
		url = 'http://psycle.sourceforge.net'
	)

netaudio = external_package_check(project, name = 'network audio system',
	dependencies = [
		cxx_build_check(project, name = 'netaudio', libraries = ['audio'], source_text = \
			"""\
				#include <audio/audiolib.h>
				void netaudio()
				{
					// todo do something with it for a complete check
				}
			"""
		)
	],
	distribution_packages = {
		'debian and ubuntu': 'libaudio-dev (>= 0)',
		'gentoo': '...',
		'fedora': '...',
		'cygwin': '...'
	},
	url = 'http://google.ch "network audio system" nas'
)

esound = external_package_check(project, name = 'esound',
	dependencies = [
		pkg_config_check(project, name = 'esound >= 0')
	],
	distribution_packages = {
		'debian and ubuntu': 'libesd0-dev (>= 0)',
		'gentoo': '...',
		'fedora': '...',
		'cygwin': '...'
	},
	url = 'http://google.ch esound' # todo check the url
)

jack = external_package_check(project, name = 'jack',
	dependencies = [
		pkg_config_check(project, name = 'jack >= 0')
	],
	distribution_packages = {
		'debian and ubuntu': 'libjack-dev (>= 0)',
		'gentoo': '...',
		'fedora': '...',
		'cygwin': '...'
	},
	url = 'http://jackaudio.net' # todo check this url
)

alsa = external_package_check(project, name = 'alsa',
	dependencies = [
		pkg_config_check(project, name = 'alsa >= 0')
	],
	distribution_packages = {
		'debian and ubuntu': 'libasound-dev (>= 0)',
		'gentoo': '...',
		'fedora': '...',
		'cygwin': '...'
	},
	url = 'http://alsa.org' # todo check this url
)

microsoft_direct_sound = external_package_check(project, name = 'microsoft direct sound',
	dependencies = [
		cxx_build_check(project, name = 'microsoft direct sound', libraries = ['dsound'], source_text = \
			"""\
				#include <dsound.h>
				void microsoft_direct_sound()
				{
					// todo do something with it for a complete check
				}
			"""
		)
	],
	distribution_packages = {'microsoft': 'direct sound'},
	url = 'http://msdn.microsoft.com'
)

# todo or not todo, asio is not "designed" to be (re)distributed
steinberg_asio = external_package_check(project, name = 'steinberg asio',
	dependencies = [
		cxx_build_check(project, name = 'steinberg asio', libraries = ['asio-is-not-even-a-library'], source_text = \
			"""\
				#include <a-bunch-of-fucked-up-headers-and-even-source-files>
				void steinberg_asio()
				{
					// todo do something with it for a complete check
				}
			"""
		)
	],
	distribution_packages = {'microsoft': 'steinberg asio'},
	url = 'http://steinberg.com'
)

# modules

from packageneric.generic.scons.module import module
class xpsycle_module(module):
	def __init__(self):
		module.__init__(self, source_package,
			name = 'xpsycle-' + str(source_package.version().major()),
			version = source_package.version(),
			description = source_package.description(),
			dependencies = [ngrs],
			target_type = module.target_types.program
		)
		
	def dynamic_dependencies(self):
		got_audio = False # flag indicating whether we have found at least one audio output lib
		
		if netaudio.result() and False: self.add_dependencies([netaudio]) ; got_audio = True # todo remove the 'and False' when netaudio suport is finished
		else: self.contexes().build().compilers().cxx().defines().add({'XPSYCLE__NO_NETAUDIO': 1})
		#self.contexes().build().compilers().cxx().defines().substituted_file(os.path.join('src', 'xpsycle', 'netaudio_conditional_build.h.in'
		
		if esound.result(): self.add_dependencies([esound]) ; got_audio = True
		else: self.contexes().build().compilers().cxx().defines().add({'XPSYCLE__NO_ESOUND': 1})
		#self.contexes().build().compilers().cxx().defines().substituted_file(os.path.join('src', 'xpsycle', 'esound_conditional_build.h.in'

		if jack.result(): self.add_dependencies([jack]) ; got_audio = True
		else: self.contexes().build().compilers().cxx().defines().add({'XPSYCLE__NO_JACK': 1})
		#self.contexes().build().compilers().cxx().defines().substituted_file(os.path.join('src', 'xpsycle', 'jack_conditional_build.h.in'
		
		if alsa.result(): self.add_dependencies([alsa]) ; got_audio = True
		else: self.contexes().build().compilers().cxx().defines().add({'XPSYCLE__NO_ALSA': 1})
		#self.contexes().build().compilers().cxx().defines().substituted_file(os.path.join('src', 'xpsycle', 'alsa_conditional_build.h.in'
		
		if microsoft_direct_sound.result(): self.add_dependencies([microsoft_direct_sound]) ; got_audio = True
		else: self.contexes().build().compilers().cxx().defines().add({'XPSYCLE__NO_MICROSOFT_DIRECT_SOUND': 1})
		#self.contexes().build().compilers().cxx().defines().substituted_file(os.path.join('src', 'xpsycle', 'microsoft_direct_sound_conditional_build.h.in'

		if steinberg_asio.result(): self.add_dependencies([steinberg_asio]) ; got_audio = True
		else: self.contexes().build().compilers().cxx().defines().add({'XPSYCLE__NO_STEINBERG_ASIO': 1})
		#self.contexes().build().compilers().cxx().defines().substituted_file(os.path.join('src', 'xpsycle', 'steinberg_asio_conditional_build.h.in'
		
		if not got_audio:
			self.project().warning(
				'None of the supported audio output libraries was found!\n' +
				'You ought to install at least one of the following packages:\n' +
				''.join([str(package) for package in netaudio, esound, jack, alsa, microsoft_direct_sound, steinberg_asio])
			)

xpsycle_module = xpsycle_module()

from packageneric.generic.scons.find import find
xpsycle_module.add_sources(find(project, 'src', 'xpsycle', '*.cpp'))
xpsycle_module.add_headers(find(project, 'src', 'xpsycle', '*.hpp'))
xpsycle_module.add_headers(find(project, 'src', 'xpsycle', '*.h'))

xpsycle_module.contexes().source().compilers().cxx().paths().add(['src'])

if False:
	# debian

	from packageneric.generic.scons.debian_package import debian_package

	xpsycle_runtime = debian_package(project,
		name = 'xpsycle-' + str(source_package.version().major()),
		section = 'audio',
		description = xpsycle_module.description(),
		long_description = 'This package contains the runtime program.'
	)
	#ngrs_runtime.add_files(ngrs_package.binaries())

	xpsycle_doc = debian_package(project,
		name = xpsycle_runtime.name() + '-doc',
		section = 'doc',
		architecture = 'all',
		description = xpsycle_module.description(),
		long_description = 'This package contains the documentation.'
	)

	from packageneric.generic.scons.debian import debian
	debian = debian(source_package,
		maintainer = prodos,
		uploaders = [prodos, bohan],
		binary_packages = [xpsycle_runtime, xpsycle_doc],
	)

plugin_modules = os.path.join('..', 'xpsycle.plugins', 'SConstruct')
if os.path.exists(plugin_modules): plugin_modules = project.subscript(plugin_modules)
else: plugin_modules = []

project([xpsycle_module] + plugin_modules)
