#! /bin/sh

# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2006-2010 members of the psycle project http://psycle.sourceforge.net ; johan boule <bohan@jabber.org>

# This script check whether a vcproj file lists all the source files

if test -z "$1"
then
	echo "$(basename $0): parameter expected: the vcproj file to check." &&
	false
fi &&
vcproj=$1 &&

if test -z "$2"
then
	echo "$(basename $0): parameter expected: the directory containing the source files." &&
	false
fi &&
src=$2 &&

tmp=/tmp/$(basename $0)-pid-$$ &&

sed -e 'y,\\,/,' -n -e 's,.*RelativePath="\.*/*\([^"]*\)".*,./\1,p' $vcproj | sort > $tmp-vcproj &&
cd $src && find . -name '*.cpp' -or -name '*.hpp' -or -name '*.h' | sort > $tmp-fs &&
diff $tmp-vcproj $tmp-fs

rm -f $tmp-*

