#! /bin/sh

for i in $(find "${@:-$(dirname $0)/..}" \( \
	-name \*.psy -or \
	-name \*.png -or \
	-name \*.jpeg -or \
	-name \*.jpg -or \
	-name \*.ico -or \
	-name \*.bmp -or \
	-name \*.cpp -or \
	-name \*.hpp -or \
	-name \*.hpp.in -or \
	-name \*.ipp -or \
	-name \*.c -or \
	-name \*.h -or \
	-name \*.h.in -or \
	-name \*.i -or \
	-name \*.rc -or \
	-name \*.xpm -or \
	-name \*.dot -or \
	-name \*.svg -or \
	-name \*.iss -or \
	-name \*.txt -or \
	-name \*.text -or \
	-name \*.html -or \
	-name \*.xml -or \
	-name \*.pro -or \
	-name \*.pri -or \
	-name \*.m4 -or \
	-name \*.ac -or \
	-name \*.am -or \
	-name \*.pc -or \
	-name \*.pc.in -or \
	-name SConstruct -or \
	-name SConscript -or \
	-name \*.sln -or \
	-name \*.vcproj -or \
	-name \*.vsprops -or \
	-name README -or \
	-name README-alpha -or \
	-name INSTALL -or \
	-name LICENSE -or \
	-name COPYING -or \
	-name AUTHORS -or \
	-name NEWS -or \
	-name TODO -or \
	-name HACKING -or \
	-name ChangeLog \
\))
do
	test -f "$i" || continue
	test -d "$(dirname $i)/.svn" || continue
	if test -x "$i"
	then
		echo chmod a-x "$i"
		chmod a-x "$i"
	fi
	if svn proplist --verbose "$i" | grep -E '^ *svn:executable : \*$' --silent
	then
		svn propdel svn:executable "$i"
	fi
done

for i in $(find "${@:-$(dirname $0)/..}" -type f -perm /+x ! -wholename \*/++\*)
do
	test -f "$i" || continue
	test -d "$(dirname $i)/.svn" || continue
	if ! svn proplist --verbose "$i" | grep -E '^ *svn:executable : \*$' --silent
	then
		svn propset svn:executable \* "$i"
	fi
done
