// -*- mode:c++; indent-tabs-mode:t -*-
// This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
// copyright 1999-2008 psycledelics http://psycle.pastnotecut.org ; johan boule <bohan@jabber.org>

#pragma once

#if !defined PACKAGENERIC
	// A "packageneric"-compliant build system defines the needed macros automatically.
	// If a different build system is used, as e.g. a dumb msvc project,
	// we have to manually define all the needed macros.
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__COMPILER__DETAIL__PRAGMATIC__DEMANGLE 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__COMPILER__EXCEPTIONS__ELLIPSIS 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__DETAIL__CHECK_VERSION 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__DYNAMIC_LINK__RESOLVER 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__EXCEPTIONS__CODE_DESCRIPTION 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__CLOCKS 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__EXCEPTION 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__LOGGERS 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__PATHS 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__OPERATING_SYSTEM__TERMINAL 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__PROCESSOR__EXCEPTION 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__PROCESSOR__ATOMIC__COMPARE_AND_SWAP 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__PROCESSOR__EXCEPTIONS__CODE_DESCRIPTION 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__PROCESSOR__EXCEPTION 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__STANDARD_LIBRARY__DETAIL__ALLOCATORS 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__STANDARD_LIBRARY__EXCEPTIONS__CODE_DESCRIPTION 1
	#define PACKAGENERIC__MODULE__SOURCE__UNIVERSALIS__EXCEPTION 1
#endif
