#! /usr/bin/env scons

# This source is free software ; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation ; either version 2, or (at your option) any later version.
# copyright 2006 johan boule <bohan@jabber.org>
# copyright 2006 psycledelics http://psycle.pastnotecut.org

# project

from packageneric.generic.scons.project import project
project = project(name = 'universalis')

# authors/maintainers/uploaders

from packageneric.generic.scons.person import person
bohan = person('Johan Boule', 'bohan.debian.universalis@retropaganda.info')

# source package

from packageneric.generic.scons.source_package import source_package
from packageneric.generic.scons.version import version
source_package = source_package(project,
	name = 'universalis',
	version = version(0, 0),
	description = 'universalis platform abstraction layer library',
	long_description = """\
universalis is a library which abstracts the few platform specificities
which are not handled by the boost and glibmm libraries themselves.
Those abstractions of platforms specificities can be categorized into:
 - tweaks for conformance with the C++ standard library
 - widespread compiler extensions to the C++ standard
 - widespread operating system features
 - widespread CPU features"""
)

import sys
sys.exit(0) # work in progress

# external packages

from packageneric.generic.scons.check.external_package import external_package as external_package_check
from packageneric.generic.scons.check.pkg_config import pkg_config as pkg_config_check

import os.path
diversalis = os.path.join('..', 'diversalis', 'SConstruct') # todo SConscript
if os.path.exists(diversalis): diversalis = SConscript(diversalis).local_package()
else:
	diversalis = external_package_check(project, name = 'diversalis',
		dependencies = [
			pkg_config_check(project, name = 'diversalis-0 >= 0')
		],
		distribution_packages = {'debian': 'lib-diversalis-0-dev (>= 0)'},
		url = 'http://psycle.sourceforge.net'
	)

from packageneric.pool.stdcxx import stdcxx
stdcxx = stdcxx(project)

from packageneric.pool.dlfcn import dlfcn
dlfcn = dlfcn(project)

from packageneric.pool.boost import boost
boost = boost(project, 103300, ['thread', 'filesystem'])

glibmm = external_package_check(project, name = 'glibmm',
	dependencies = [
		pkg_config_check(project, name = 'glibmm-2.4 >= 2.4 gmodule-2.0 >= 2.0 gthread-2.0 >= 2.0')
	],
	distribution_packages = {
		'debian': 'libglibmm-2.4-dev (>= 2.4)',
		'cygwin': 'glib2-devel-2.6.6-2' # mm!
	},
	url = 'http://freedesktops.org'
)

# modules

from packageneric.generic.scons.module import module
universalis = module(source_package,
	name = 'universalis-' + str(source_package.version().major()),
	version = source_package.version(),
	description = source_package.description(),
	depends = [diversalis, glibmm, boost]
)

from packageneric.generic.scons.find import find
universalis.add_sources(find(packageneric, 'src', 'universalis', '*.cpp'))
universalis.add_headers(find(packageneric, 'src', 'universalis', '*.hpp'))

universalis.add_include_path('src', build = True, uninstalled = True)

# pkg-config packages

from packageneric.generic.scons.pkg_config_package import pkg_config_package
universalis_package = pkg_config_package(project,
	name = 'universalis-' + str(universalis.version().major()),
	version = universalis.version(),
	description = universalis.description(),
	modules = [universalis]
)

# debian

from packageneric.generic.scons.debian_package import debian_package

universalis_runtime = debian_package(project,
	name = 'lib-universalis-' + str(source_package.version().major()),
	section = 'libs',
	description = universalis_package.description(),
	long_description = 'This package contains the runtime library.'
)
#universalis_runtime.add_files(universalis_package.binaries())

class universalis_dev(debian_package):
	def __init__(self):
		debian_package.__init__(self, project,
			name = universalis_runtime.name() + '-dev',
			section = 'libdevel',
			description = universalis_package.description(),
			long_description = 'This package contains the development files.',
		)
	def dynamirc_dependencies(self):
		self.add_depend(universalis_runtime)
		self.add_build_depends(universalis_package.build_depends())
universalis_dev = universalis_dev()
#universalis_dev.add_files(universalis_package.headers())
#universalis_dev.add_files(universalis_package.pkg_config())

universalis_doc = debian_package(project,
	name = universalis_runtime.name() + '-doc',
	section = 'doc',
	architecture = 'all',
	description = universalis_package.description(),
	long_description = 'This package contains the documentation.'
)

from packageneric.generic.scons.debian import debian
debian = debian(source_package,
	maintainer = bohan,
	binary_packages = [universalis_runtime, universalis_dev, universalis_doc],
)

project(universalis_package)
